# **Data and AI in Economics: CEO Turnover and Executive Pay Dispersion in Europe: Evidence from Leadership Changes**

# **Table of Contents**

## [**1. Team**](#1-team)

## [**2. Research Framework**](#2-research-framework)

- [2.1 Research Title, Research Question and Motivation](#21-research-title-research-question-and-motivation)

- [2.2 Datasets and Key Variables](#22-datasets-and-key-variables)

  - [2.2.1 Sources](#221-sources)

  - [2.2.2 Key Variables](#222-key-variables)

  - [2.2.3 Dataset Preview](#223-dataset-preview)

- [2.3 Analytic Approach](#23-analytic-approach)

  - [2.3.1 Causal Inference](#231-causal-inference)

  - [2.3.2 Supervised Learning](#232-supervised-learning)

  - [2.3.3 Unsupervised Learning](#233-unsupervised-learning)

- [2.4 Evaluation Metric](#24-evaluation-metric)

- [2.5 Research Work Plan](#25-research-work-plan)

## [**3. Setup**](#3-setup)

- [3.1 Imports and Path Configuration](#31-imports-and-path-configuration)

- [3.2 Helper Functions](#32-helper-functions)

## [**3. Data Understanding (Exploratory Data Analysis)**](#3-data-understanding-exploratory-data-analysis)

- [3.1 Data Inspection and Descriptive Statistics](#31-data-inspection-and-descriptive-statistics)

- [3.2 Data Visualization](#32-data-visualization)

## [**4. Data Preprocessing**](#4-data-preprocessing)

- [4.1 Data Cleaning](#41-data-cleaning)

  - [4.1.1 Missing Values](#411-missing-values)

  - [4.1.2 Duplicated Values](#412-duplicated-values)

  - [4.1.3 Outliers](#413-outliers)

- [4.2 Feature Selection](#42-feature-selection)

## [**5. Causal Inference**](#5-causal-inference)

## [**6. Supervised Learning**](#6-supervised-learning)

## [**7. Unsupervised Learning**](#7-unsupervised-learning)

## [**8. Results and Conclusion**](#8-results-and-conclusion)

---

## **1. Team**

| Role | Name | Student ID |
|------|------|------------|
| Lead |Achmad Rizky Akbar| |
| Member | Kajetan Zduńczyk| |

---

## **2. Research Framework**

### **2.1 Research Title, Research Question and Motivation**

**Research Title:** *CEO Turnover and Executive Pay Dispersion in Europe: Evidence from Leadership Changes*

**Research Question:** *Does CEO turnover causally change CEO compensation levels and pay dispersion within European firms?*

**Research Motivation:** *By focusing on leadership changes observed in BoardEx, we can estimate how compensation responds to a governance shock without hand‑collecting policy data. This helps investors and regulators understand whether turnover acts as a disciplining mechanism on executive pay and internal pay gaps.*

### **2.2 Datasets and Key Variables**

#### **2.2.1 Sources**

1. **BoardEx - Individual Profile Employment**

    Includes data about Individual Profile Employment for executives in the BoardEx (Europe) universe.

    https://wrds-www.wharton.upenn.edu/pages/get-data/boardex/boardex-europe/individual-profile/individual-profile-employment/

2. **BoardEx - Individual Profile Details**

    Includes data about Individual Profile Details for executives in the BoardEx (Europe) universe.

    https://wrds-www.wharton.upenn.edu/pages/get-data/boardex/boardex-europe/individual-profile/individual-profile-details/

3. **Company Profile Details - BoardEx (Wharton Data Research Services)**

    Company Profile Details includes data such as location, market cap, and sector.
    
    https://wrds-www.wharton.upenn.edu/pages/get-data/boardex/boardex-europe/company-profile/company-profile-details/

4. **Fundamentals Annual - Compustat Global (Wharton Data Research Services)**

    Provides fundamental annual company information
    
    https://wrds-www.wharton.upenn.edu/pages/get-data/compustat-capital-iq-standard-poors/compustat/global-daily/fundamentals-annual/

5. **Annual Remuneration - BoardEx (Wharton Data Research Services):**
    
    Data such as salary, bonus, and other cash compensation
    
    https://wrds-www.wharton.upenn.edu/pages/get-data/boardex/boardex-europe/compensation-analysis/annual-remuneration/

6. **Firms in Stoxx 600 Index**

    STOXX 600 is a major stock index representing the performance of 600 large-, mid-, and small-capitalization companies across 17 developed European countries.

    https://www.stoxx.com/selection-lists

**Unit of observation:** *Executive–year within a firm (linked to firm-year fundamentals and leadership changes).*

#### **2.2.2 Key Variables**

| Variable | Type | Role (feature / target / instrument / ...) | Description |
|----------|------|---------------------------------------------|-------------|
| Total CEO compensation | Numeric | **Target** | Total annual compensation (salary + bonus + other cash/stock, in EUR) |
| Pay dispersion | Numeric | **Target / Outcome** | CEO pay relative to top-executive team (e.g., CEO-to-top-5 ratio) |
| CEO turnover indicator | Binary | **Treatment** | Flag for CEO change in a given year (from BoardEx role start/end) |
| Post‑turnover period | Binary | Feature | Indicator for years after turnover (event window) |
| Firm size (log assets / market cap) | Numeric | Feature | Scale and visibility of firm |
| Profitability (ROA / EBIT margin) | Numeric | Feature | Performance controls |
| Leverage | Numeric | Feature | Capital structure |
| Industry & country fixed effects | Categorical | Feature | Sector and institutional context |
| Executive tenure | Numeric | Feature | Human capital and bargaining power |

**Potential data quality issues:**  
- **Missing compensation components:** use multiple imputation or restrict to firms with complete pay breakdowns; report sensitivity to this choice.
- **Turnover date ambiguity:** define CEO change using role start/end dates and validate with overlapping roles; conduct robustness with alternative windows.
- **Reporting bias / top-coding:** winsorize extreme pay values; compare distributions by country to detect systematic reporting differences.
- **Selection bias in BoardEx coverage:** include a Stoxx 600 filter and check representativeness vs. population benchmarks.
- **Timing misalignment:** align fiscal-year fundamentals with compensation year; drop or lag inconsistent observations.
- **Currency and inflation effects:** convert to EUR and deflate using CPI to ensure comparability across years.

#### **2.2.3 Dataset Preview**

**1. Import pre installed WRDS package**

In [2]:
import wrds

import numpy as np
import pandas as pd
from pathlib import Path

**2. Establish connection with WRDS server**

- log in using your WRDS username and password

- set up a pgpass file to store the info

In [3]:
conn = wrds.Connection()

WRDS recommends setting up a .pgpass file.
Created .pgpass file successfully.
You can create this file yourself at any time with the create_pgpass_file() function.
Loading library list...
Done

**3. List all libraries**

- "Library" refers to databases on WRDS: e.g. CRSP, Compustat

- list_libraries() function to explore all subscribed databases

In [4]:
conn.list_libraries()

['aha_sample',
 'ahasamp',
 'auditsmp',
 'auditsmp_all',
 'bank',
 'bank_all',
 'bank_premium_samp',
 'banksamp',
 'block',
 'block_all',
 'boardex',
 'boardex_eur',
 'boardex_na',
 'boardex_trial',
 'boardex_uk',
 'boardsmp',
 'bvd_amadeus_trial',
 'bvd_bvdbankf_trial',
 'bvd_orbis_trial',
 'bvdsamp',
 'calcbench_trial',
 'calcbnch',
 'candid_samp',
 'cboe',
 'cboe_all',
 'cboe_sample',
 'cboesamp',
 'cddsamp',
 'ciq',
 'ciq_common',
 'ciq_keydev',
 'ciq_transactions',
 'ciqsamp',
 'ciqsamp_capstrct',
 'ciqsamp_common',
 'ciqsamp_keydev',
 'ciqsamp_pplintel',
 'ciqsamp_ratings',
 'ciqsamp_transactions',
 'ciqsamp_transcripts',
 'cisdmsmp',
 'columnar',
 'comp',
 'comp_bank_daily',
 'comp_execucomp',
 'comp_global_daily',
 'comp_na_daily_all',
 'comp_segments_hist_daily',
 'comp_snapshot',
 'compsamp',
 'compsamp_all',
 'compsamp_computext',
 'compsamp_snapshot',
 'compseg',
 'compsnap',
 'contrib',
 'contrib_as_filed_financials',
 'contrib_ceo_turnover',
 'contrib_corporate_culture',
 'contrib_general',
 'contrib_liva',
 'crspsamp',
 'crspsamp_all',
 'crspsamp_mf',
 'csmsamp_all',
 'djones',
 'djones_all',
 'dmef',
 'dmef_all',
 'doe',
 'doe_all',
 'etfg_samp',
 'etfgsamp',
 'execcomp',
 'factsamp_all',
 'factsamp_revere',
 'ff',
 'ff_all',
 'fisdsamp',
 'fisdsamp_all',
 'fjc',
 'fjc_linking',
 'fjc_litigation',
 'frb',
 'frb_all',
 'fssamp',
 'ftsesamp',
 'ftsesamp_russell_us',
 'gutenberg',
 'hfrsamp',
 'hfrsamp_hfrdb',
 'ibessamp_kpi',
 'ifgrsamp',
 'infasamp',
 'infogroupsamp_business',
 'infogroupsamp_residential',
 'infraclear_samp',
 'insdsamp',
 'iri',
 'iri_all',
 'kpisamp',
 'macrofin',
 'macrofin_comm_trade',
 'midas',
 'morningstarsamp_cisdm',
 'mpsych_sample',
 'mrktsamp',
 'mrktsamp_cds',
 'mrktsamp_cdx',
 'mrktsamp_msf',
 'mrktsamp_red',
 'msci_climate_samp',
 'msci_common_samp',
 'msci_esg_samp',
 'mscicoms',
 'mscicsmp',
 'msciesmp',
 'msrb',
 'msrb_all',
 'msrbsamp',
 'msrbsamp_all',
 'omtrial',
 'optionmsamp_europe',
 'optionmsamp_us',
 'otc',
 'otc_endofday',
 'panjiva_samp',
 'phlx',
 'phlx_all',
 'pitchsmp',
 'pnjvasmp',
 'preqsamp',
 'preqsamp_all',
 'public',
 'public_all',
 'pwt',
 'pwt_all',
 'reprisk',
 'reprisk_common',
 'reprisk_pm',
 'reprisk_sample',
 'reprisk_std',
 'reprisk_v2',
 'repsamp',
 'revelio_samp',
 'revsamp',
 'risksamp',
 'risksamp_all',
 'rq_all',
 'rstat_samp',
 'rstatsmp',
 'sdcsamp',
 'shvlsamp',
 'snapsamp',
 'snlsamp',
 'snlsamp_fig',
 'sustainalyticssamp_all',
 'sustsamp',
 'taqmsamp',
 'taqmsamp_all',
 'taqsamp',
 'taqsamp_all',
 'totalq',
 'totalq_all',
 'tr_sdc_samples',
 'trace',
 'trace_enhanced',
 'trace_standard',
 'trcstsmp',
 'trdbdmismp',
 'trdbwbsmp',
 'trdssamp',
 'tresgsmp',
 'trsamp',
 'trsamp_all',
 'trsamp_db_dmi',
 'trsamp_db_wb',
 'trsamp_ds_eq',
 'trsamp_dscom',
 'trsamp_dsecon',
 'trsamp_dsfut',
 'trsamp_esg',
 'trsamp_sdc_ma',
 'trsamp_sdc_ni',
 'trsamp_worldscope',
 'trucost_samp',
 'twoiq_samp',
 'twoiqsmp',
 'wabssamp',
 'wappsamp',
 'wenvsmp',
 'wmfsmp',
 'wrds_abs_samp',
 'wrds_environmental_samp',
 'wrds_insiders_samp',
 'wrds_mutualfund_samp',
 'wrds_shortvolume_samp',
 'wrdsapps',
 'wrdsapps_eushort',
 'wrdsapps_evtstudy_int',
 'wrdsapps_link_comp_eushort',
 'wrdsapps_patents',
 'wrdsapps_plink_exec_boardex',
 'wrdsapps_subsidiary',
 'wrdsapps_windices',
 'wrdsappssamp_all',
 'wrdssec_midas',
 'zacksamp',
 'zacksamp_all']

In [5]:
df_db = pd.DataFrame(conn.list_libraries(), columns=['subbed_db']).sort_values(by='subbed_db', ascending=True)
df_db

             subbed_db
0           aha_sample
1              ahasamp
2             auditsmp
3         auditsmp_all
4                 bank
..                 ...
204  wrdsapps_windices
205   wrdsappssamp_all
206      wrdssec_midas
207           zacksamp
208       zacksamp_all

[209 rows x 1 columns]

In [6]:
with pd.option_context("display.max_rows", None):
    print(df_db)

                       subbed_db
0                     aha_sample
1                        ahasamp
2                       auditsmp
3                   auditsmp_all
4                           bank
5                       bank_all
6              bank_premium_samp
7                       banksamp
8                          block
9                      block_all
10                       boardex
11                   boardex_eur
12                    boardex_na
13                 boardex_trial
14                    boardex_uk
15                      boardsmp
16             bvd_amadeus_trial
17            bvd_bvdbankf_trial
18               bvd_orbis_trial
19                       bvdsamp
20               calcbench_trial
21                      calcbnch
22                   candid_samp
23                          cboe
24                      cboe_all
25                   cboe_sample
26                      cboesamp
27                       cddsamp
28                           ciq
29                    ciq_common
30                    ciq_keydev
31              ciq_transactions
32                       ciqsamp
33              ciqsamp_capstrct
34                ciqsamp_common
35                ciqsamp_keydev
36              ciqsamp_pplintel
37               ciqsamp_ratings
38          ciqsamp_transactions
39           ciqsamp_transcripts
40                      cisdmsmp
41                      columnar
42                          comp
43               comp_bank_daily
44                comp_execucomp
45             comp_global_daily
46             comp_na_daily_all
47      comp_segments_hist_daily
48                 comp_snapshot
49                      compsamp
50                  compsamp_all
51            compsamp_computext
52             compsamp_snapshot
53                       compseg
54                      compsnap
55                       contrib
56   contrib_as_filed_financials
57          contrib_ceo_turnover
58     contrib_corporate_culture
59               contrib_general
60                  contrib_liva
61                      crspsamp
62                  crspsamp_all
63                   crspsamp_mf
64                   csmsamp_all
65                        djones
66                    djones_all
67                          dmef
68                      dmef_all
69                           doe
70                       doe_all
71                     etfg_samp
72                      etfgsamp
73                      execcomp
74                  factsamp_all
75               factsamp_revere
76                            ff
77                        ff_all
78                      fisdsamp
79                  fisdsamp_all
80                           fjc
81                   fjc_linking
82                fjc_litigation
83                           frb
84                       frb_all
85                        fssamp
86                      ftsesamp
87           ftsesamp_russell_us
88                     gutenberg
89                       hfrsamp
90                 hfrsamp_hfrdb
91                  ibessamp_kpi
92                      ifgrsamp
93                      infasamp
94        infogroupsamp_business
95     infogroupsamp_residential
96               infraclear_samp
97                      insdsamp
98                           iri
99                       iri_all
100                      kpisamp
101                     macrofin
102          macrofin_comm_trade
103                        midas
104        morningstarsamp_cisdm
105                mpsych_sample
106                     mrktsamp
107                 mrktsamp_cds
108                 mrktsamp_cdx
109                 mrktsamp_msf
110                 mrktsamp_red
111            msci_climate_samp
112             msci_common_samp
113                msci_esg_samp
114                     mscicoms
115                     mscicsmp
116                     msciesmp
117                         msrb
118                     msrb_all
119                     msrbsamp
120                 msrbsamp_all
121                      omtrial
122           optionmsamp_europe
123               optionmsamp_us
124                          otc
125                 otc_endofday
126                 panjiva_samp
127                         phlx
128                     phlx_all
129                     pitchsmp
130                     pnjvasmp
131                     preqsamp
132                 preqsamp_all
133                       public
134                   public_all
135                          pwt
136                      pwt_all
137                      reprisk
138               reprisk_common
139                   reprisk_pm
140               reprisk_sample
141                  reprisk_std
142                   reprisk_v2
143                      repsamp
144                 revelio_samp
145                      revsamp
146                     risksamp
147                 risksamp_all
148                       rq_all
149                   rstat_samp
150                     rstatsmp
151                      sdcsamp
152                     shvlsamp
153                     snapsamp
154                      snlsamp
155                  snlsamp_fig
156       sustainalyticssamp_all
157                     sustsamp
158                     taqmsamp
159                 taqmsamp_all
160                      taqsamp
161                  taqsamp_all
162                       totalq
163                   totalq_all
164               tr_sdc_samples
165                        trace
166               trace_enhanced
167               trace_standard
168                     trcstsmp
169                   trdbdmismp
170                    trdbwbsmp
171                     trdssamp
172                     tresgsmp
173                       trsamp
174                   trsamp_all
175                trsamp_db_dmi
176                 trsamp_db_wb
177                 trsamp_ds_eq
178                 trsamp_dscom
179                trsamp_dsecon
180                 trsamp_dsfut
181                   trsamp_esg
182                trsamp_sdc_ma
183                trsamp_sdc_ni
184            trsamp_worldscope
185                 trucost_samp
186                   twoiq_samp
187                     twoiqsmp
188                     wabssamp
189                     wappsamp
190                      wenvsmp
191                       wmfsmp
192                wrds_abs_samp
193      wrds_environmental_samp
194           wrds_insiders_samp
195         wrds_mutualfund_samp
196        wrds_shortvolume_samp
197                     wrdsapps
198             wrdsapps_eushort
199        wrdsapps_evtstudy_int
200   wrdsapps_link_comp_eushort
201             wrdsapps_patents
202  wrdsapps_plink_exec_boardex
203          wrdsapps_subsidiary
204            wrdsapps_windices
205             wrdsappssamp_all
206                wrdssec_midas
207                     zacksamp
208                 zacksamp_all

**4. List all datasets within a given library**

- databases contain many sub datasets

- list_tables() function to list all datasets

- specify which "library/database"

In [7]:
conn.list_tables(library='boardex_eur')

['eur_board_characteristics',
 'eur_board_dir_announcements',
 'eur_board_dir_committees',
 'eur_board_education_assoc',
 'eur_board_listed_assoc',
 'eur_board_nfp_assoc',
 'eur_board_other_assoc',
 'eur_board_unlisted_assoc',
 'eur_company_profile_advisors',
 'eur_company_profile_details',
 'eur_company_profile_market_cap',
 'eur_company_profile_sr_mgrs',
 'eur_company_profile_stocks',
 'eur_dir_characteristics',
 'eur_dir_education_assoc',
 'eur_dir_listed_assoc',
 'eur_dir_nfp_assoc',
 'eur_dir_other_assoc',
 'eur_dir_profile_achievements',
 'eur_dir_profile_details',
 'eur_dir_profile_education',
 'eur_dir_profile_emp',
 'eur_dir_profile_other_activ',
 'eur_dir_standard_remun',
 'eur_dir_unlisted_assoc',
 'eur_lookupcompany',
 'eur_lookuproles',
 'eur_lookupsalutations',
 'eur_ltip_compensation',
 'eur_ltip_wealth',
 'eur_options_compensation',
 'eur_options_wealth',
 'eur_wrds_company_dir_names',
 'eur_wrds_company_names',
 'eur_wrds_company_networks',
 'eur_wrds_company_profile',
 'eur_wrds_company_region',
 'eur_wrds_dir_profile_all',
 'eur_wrds_dir_profile_emp',
 'eur_wrds_individual_networks',
 'eur_wrds_org_composition',
 'eur_wrds_org_summary']

**5. Query Data from WRDS Server**

- get_table() method

- straightforward if getting data from one single dataset

- specify which library/database and table/dataset to "get"

- can slice data by:
    - number of rows

    - column names

In [8]:
# Extract first 5 obs from comp.company

company = conn.get_table(library='comp', table='company', obs=5)
company

,conm,gvkey,add1,add2,add3,add4,addzip,busdesc,cik,city,...,sic,spcindcd,spcseccd,spcsrc,state,stko,weburl,dldte,ipodate,curr_sp500_flag
0,A & E PLASTIK PAK INC,001000,<NA>,<NA>,<NA>,<NA>,<NA>,A & E Plastik Pak Inc. is a commodity chemical...,<NA>,<NA>,...,3089,325,978,<NA>,<NA>,0,<NA>,1978-06-30,<NA>,0.0
1,A & M FOOD SERVICES INC,001001,1924 South Utica Avenue,<NA>,<NA>,<NA>,94104,<NA>,0000723576,Tulsa,...,5812,420,978,<NA>,OK,0,<NA>,1986-07-31,<NA>,0.0
2,AAI CORP,001002,124 Industry Lane,<NA>,<NA>,<NA>,21030-0126,"Textron Systems Corporation designs, develops,...",0001306124,Hunt Valley,...,3825,230,940,<NA>,MD,0,www.textronsystems.com,1977-03-31,<NA>,0.0
3,A.A. IMPORTING CO INC,001003,7700 Hall Street,<NA>,<NA>,<NA>,63125,"A.A. Importing Company, Inc. designs, manufact...",0000730052,St. Louis,...,5712,449,976,<NA>,MO,3,www.aaimporting.com,1992-04-30,<NA>,0.0
4,AAR CORP,001004,"One AAR Place, 1100 North Wood Dale Road",<NA>,<NA>,<NA>,60191,AAR Corp. provides products and services to co...,0000001750,Wood Dale,...,5080,110,925,B,IL,0,www.aarcorp.com,<NA>,1972-04-24,0.0

In [9]:
# eur_wrds_dir_profile_emp

df_emp = conn.get_table(library='boardex_eur', table='eur_wrds_dir_profile_emp', obs = 10)
df_emp

,rowtype,directorname,companyname,datestartrole,dateendrole,brdposition,rolename,fulltextdescription,ned,leadershipteam,primarykeyid,directorid,companyid,datestartroleflag,dateendroleflag,hocountryname,sector,orgtype,isin
0,Unlisted Organisations,Killko Caballero,US Dry Cleaning Corp (First Virtual Communicat...,2001-06-19,2002-10-28,Inside,President/CEO,<NA>,No,No,1731622.0,482055.0,9.0,10.0,15.0,United States,Consumer Services,Private,<NA>
1,Listed Organisations,William Burgess,FIRST ACTIVE PLC (De-listed 01/2004),1900-01-01,9999-12-31,Yes,NED,<NA>,Yes,No,1312708.0,328039.0,10.0,75.0,80.0,Republic Of Ireland,<NA>,Quoted,<NA>
2,Listed Organisations,Doctor António Palma Ramalho,FIRST ACTIVE PLC (De-listed 01/2004),1900-01-01,9999-12-31,Yes,Director - SD,<NA>,Yes,No,5617768.0,885377.0,10.0,75.0,80.0,Republic Of Ireland,<NA>,Quoted,<NA>
3,Listed Organisations,Clodagh NicCanna,FIRST ACTIVE PLC (De-listed 01/2004),1900-01-01,9999-12-31,No,Executive,<NA>,No,No,16213573.0,2765991.0,10.0,75.0,80.0,Republic Of Ireland,<NA>,Quoted,<NA>
4,Listed Organisations,Dick Milliken,FIRST ACTIVE PLC (De-listed 01/2004),1998-11-11,2004-01-28,Yes,NED,<NA>,Yes,No,2104000.0,512347.0,10.0,10.0,15.0,Republic Of Ireland,<NA>,Quoted,<NA>
5,Listed Organisations,John Callaghan,FIRST ACTIVE PLC (De-listed 01/2004),1999-04-01,2004-12-31,Yes,Chairman,<NA>,Yes,No,1146627.0,2763.0,10.0,20.0,25.0,Republic Of Ireland,<NA>,Quoted,<NA>
6,Listed Organisations,John Callaghan,FIRST ACTIVE PLC (De-listed 01/2004),1993-01-02,1997-12-31,Yes,NED,<NA>,Yes,No,1146623.0,2763.0,10.0,30.0,25.0,Republic Of Ireland,<NA>,Quoted,<NA>
7,Listed Organisations,John Callaghan,FIRST ACTIVE PLC (De-listed 01/2004),1997-01-02,1999-04-28,Yes,Vice Chairman,<NA>,Yes,No,1146624.0,2763.0,10.0,30.0,15.0,Republic Of Ireland,<NA>,Quoted,<NA>
8,Unlisted Organisations,Captain Aaron Bresnahan,First Agate Capital Corp,1993-06-01,1999-03-28,No,Various Positions,Maritime,No,No,6718065.0,880720.0,11.0,20.0,15.0,United States,Speciality & Other Finance,Private,<NA>
9,Unlisted Organisations,Adam Ebrahim,First Agate Capital Corp,1900-01-01,9999-12-31,Yes,Director - SD,<NA>,Yes,No,7328579.0,1261572.0,11.0,75.0,80.0,United States,Speciality & Other Finance,Private,<NA>

---

In [10]:
import numpy as np
import pandas as pd
from pathlib import Path

In [11]:
DATA_DIR = Path("..") / ".." / "data" / "data_project"

In [12]:
DATA_DIR = Path("../data")

df_emp = pd.read_csv(DATA_DIR / "executives_employment.csv")
df_emp.head(3)

,isin,datestartrole,directorname,companyname,dateendrole,brdposition,rolename,fulltextdescription,ned,primarykeyid,directorid,companyid,hocountryname
0,GB00B1YW4409,1900-01-01,John Yetman,3I GROUP PLC,9999-12-31,No,Executive,Investment Executive,No,1654504,8428,294,United Kingdom - England
1,GB00B1YW4409,2005-07-06,Rod Perry,3I GROUP PLC,9999-12-31,No,Consultant,Also Head of International Advisory Board of V...,No,2003633,11777,294,United Kingdom - England
2,GB00B1YW4409,1900-01-01,John De Zulueta Greenebaum,3I GROUP PLC,9999-12-31,No,Advisor,NaN,No,2542008,6474,294,United Kingdom - England

**1. Individual Profile Employment**

In [13]:
# Individual Profile Employment
df_emp = pd.read_csv(DATA_DIR / "executives_employment.csv")
df_emp.head(3)

,isin,datestartrole,directorname,companyname,dateendrole,brdposition,rolename,fulltextdescription,ned,primarykeyid,directorid,companyid,hocountryname
0,GB00B1YW4409,1900-01-01,John Yetman,3I GROUP PLC,9999-12-31,No,Executive,Investment Executive,No,1654504,8428,294,United Kingdom - England
1,GB00B1YW4409,2005-07-06,Rod Perry,3I GROUP PLC,9999-12-31,No,Consultant,Also Head of International Advisory Board of V...,No,2003633,11777,294,United Kingdom - England
2,GB00B1YW4409,1900-01-01,John De Zulueta Greenebaum,3I GROUP PLC,9999-12-31,No,Advisor,NaN,No,2542008,6474,294,United Kingdom - England

**2. Individual Profile Details**

In [14]:
# Individual Profile Details
df_exec_old = pd.read_csv(DATA_DIR / "executives_profile.csv")
df_exec_old.head()

/var/folders/yj/b9f3mv7j0bq585tjqs9_xgb00000gn/T/ipykernel_39384/2155953239.py:2: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  df_exec_old = pd.read_csv(DATA_DIR / "executives_profile.csv")

,directorid,directorname,title,forename1,forename2,forename3,forename4,usualname,surname,suffixtitle,...,dod,age,gender,recreations,directorvisible,dobflag,dodflag,wealthxid,primaryroleid,networksize
0,16,David Shaw,Mr,David,Evans,NaN,NaN,NaN,Shaw,MBA,...,9999-12-31,74.0,M,NaN,Yes,10,55,112260.0,1083314.0,5675.0
1,36,Kevin Kelly,Mr,Kevin,John,NaN,NaN,NaN,Kelly,FCA FCIB,...,2012-01-04,70.0,M,NaN,Yes,10,10,2247015.0,7117.0,NaN
2,37,Klaus Zwickel,Mr,Klaus,NaN,NaN,NaN,NaN,Zwickel,NaN,...,9999-12-31,86.0,M,NaN,Yes,10,55,NaN,3.0,468.0
3,39,Doctor Christopher Albrecht,Doctor,Christopher,J,C,NaN,NaN,Albrecht,PhD,...,9999-12-31,87.0,M,NaN,Yes,10,55,NaN,50962.0,78.0
4,42,Umberto Agnelli,Mr,Umberto,NaN,NaN,NaN,NaN,Agnelli,NaN,...,2004-05-27,69.0,M,NaN,Yes,10,10,NaN,133504.0,NaN

**3. Company Profile Details**

In [15]:
# Company Profile Details
df_firm = pd.read_csv(DATA_DIR / "company_profile.csv")
df_firm.head()

/var/folders/yj/b9f3mv7j0bq585tjqs9_xgb00000gn/T/ipykernel_39384/1818324475.py:2: DtypeWarning: Columns (9,10,14,15,16,17,18,19,20,21,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df_firm = pd.read_csv(DATA_DIR / "company_profile.csv")

,isin,boardname,boardnameshort,hoaddress1,hoaddress2,hoaddress3,hoaddress4,hoaddress5,hocountryname,hotelnumber,...,successorcompanyid,ultimateparentcompanyid,boardid,ticker,countryofquote,primarystock,currency,mktcapitalisation,noemployees,revenue
0,NaN,1955 INVERSIONES SIMCAV SA,1955 INVERSIONES SIMCAV SA,NaN,NaN,NaN,NaN,NaN,Spain,NaN,...,NaN,NaN,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,FIRST ACTIVE PLC (De-listed 01/2004),FIRST ACTIVE PLC,NaN,NaN,NaN,NaN,NaN,Republic Of Ireland,NaN,...,783081.0,NaN,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,FIRST EAGLE FUND NV (De-listed 10/2011),FIRST EAGLE FUND NV,NaN,NaN,NaN,NaN,NaN,Netherlands Antilles,NaN,...,NaN,NaN,88,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,2M INVEST A/S,2M INVEST A/S,NaN,NaN,NaN,NaN,NaN,Denmark,NaN,...,NaN,NaN,264,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,GB0004618236,THREADNEEDLE UK SELECT TRUST LTD (UK Select Tr...,THREADNEEDLE UK SELECT TRUST LTD,Ground Floor Dorey Court,Admiral Park,St Peter Port,NaN,GY1 2HT,Guernsey,+44 (0)1 481 727 111,...,NaN,NaN,296,UKT,ENGLAND AND WALES,Yes,NaN,NaN,NaN,NaN

In [16]:
display(df_firm.describe())
display(df_firm.describe(include="object"))

,companypolicy,cikcode,previouscompanyid,successorcompanyid,boardid,mktcapitalisation,noemployees,revenue
count,0.0,1.041000e+03,6.901000e+03,6.593000e+03,4.450040e+05,4770.000000,4.383000e+03,4489.00000
mean,NaN,1.426868e+06,2.082375e+06,2.493534e+06,2.397661e+06,6238.678826,1.278777e+04,4566.55714
std,NaN,3.652228e+05,1.226734e+06,1.085201e+06,1.074114e+06,29254.949981,6.514137e+04,17911.67812
min,NaN,1.970000e+03,1.000000e+01,5.540000e+02,8.000000e+00,0.000000,1.000000e+00,0.00000
25%,NaN,1.167379e+06,1.141672e+06,1.703653e+06,1.673212e+06,78.000000,1.585000e+02,46.00000
50%,NaN,1.475011e+06,2.213311e+06,2.652171e+06,2.567914e+06,308.500000,1.015000e+03,336.00000
75%,NaN,1.665584e+06,3.182669e+06,3.426112e+06,3.275926e+06,1771.500000,6.105000e+03,2116.00000
max,NaN,2.079106e+06,4.100544e+06,4.101470e+06,4.101635e+06,563017.000000,2.476748e+06,336131.00000

,isin,boardname,boardnameshort,hoaddress1,hoaddress2,hoaddress3,hoaddress4,hoaddress5,hocountryname,hotelnumber,...,ccfaxnumber,sector,index,orgvisible,orgtype,ultimateparentcompanyid,ticker,countryofquote,primarystock,currency
count,6824,445004,445004,16905,12348,3593,14882,16462,445004,2698,...,2187,172966,1244,445004,445004,41559,6399,6823,6824,6408
unique,6677,444245,443604,14108,6404,1783,516,7563,55,2294,...,1907,52,89,2,10,10857,5914,50,2,1
top,LU0569974404,NB DISTRESSED DEBT INVESTMENT FUND LTD,NB DISTRESSED DEBT INVESTMENT FUND LTD,1 Royal Plaza,Amsterdam,Saint Peter Port,Paris,75008,Germany,+44 (0) 4 8175 0800,...,+46 (0) 8 735 57 44,Business Services,CDAX,No,Private,24776,TEL,FRANCE,Yes,USD
freq,4,12,12,28,243,139,1396,310,64496,12,...,7,21510,235,436587,389333,173,5,936,6230,6408

**4. Annual Renumeration**

In [17]:
# Annual Renumeration
df_renum_old = pd.read_csv(DATA_DIR / "annual_renumeration.csv")
df_renum_old.head()

,boardid,annualreportdate,rowtype,boardname,ned,directorname,rolename,currency,rolestatus,remchgelast,...,ltipvalue,intrvaloptaward,estvaloptaward,toteqatrisk,totremperiod,bonusratio,eqlinkremratio,wealthdelta,totaldirectcomp,perftotal
0,296,2016-12-01,SD Average,THREADNEEDLE UK SELECT TRUST LTD (UK Select Tr...,Yes,NaN,NaN,USD,NaN,0.14,...,NaN,NaN,NaN,NaN,35.0,NaN,NaN,2.0,35.0,NaN
1,296,2017-06-01,SD Average,THREADNEEDLE UK SELECT TRUST LTD (UK Select Tr...,Yes,NaN,NaN,USD,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,296,2017-06-01,Board Average,THREADNEEDLE UK SELECT TRUST LTD (UK Select Tr...,No,NaN,NaN,USD,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,296,2016-12-01,Board Average,THREADNEEDLE UK SELECT TRUST LTD (UK Select Tr...,No,NaN,NaN,USD,NaN,0.14,...,NaN,NaN,NaN,NaN,35.0,NaN,NaN,2.0,35.0,NaN
4,296,2017-06-01,SD Total,THREADNEEDLE UK SELECT TRUST LTD (UK Select Tr...,Yes,NaN,NaN,USD,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**5. Firms in Stoxx 600 Index**

In [18]:
# Firms in EuroStoxx 600 Index
df_sxxp = pd.read_csv(DATA_DIR / "stoxx600_clean.csv", sep=";")
df_sxxp.head()

,Creation_Date,Internal_Key,ISIN,RIC,Instrument_Name,Country,Currency,Exchange,Index Membership,Rank (FINAL)
0,20260501,546078,NL0010273215,ASML.AS,ASML HLDG,NL,EUR,Euronext Amsterdam,Large,1
1,20260501,40054,GB0005405286,HSBA.L,HSBC,GB,GBP,London SE,Large,2
2,20260501,98952,GB0009895292,AZN.L,ASTRAZENECA,GB,GBP,London SE,Large,3
3,20260501,474577,CH0012032048,ROPC.S,ROCHE PS,CH,CHF,Six Swiss Exchange,Large,4
4,20260501,477408,CH0012005267,NOVN.S,NOVARTIS,CH,CHF,Six Swiss Exchange,Large,5

In [19]:
display(df_sxxp.describe())
display(df_sxxp.describe(include="object"))

       Creation_Date  Rank (FINAL)
count          600.0    600.000000
mean      20260501.0    300.500000
std              0.0    173.349358
min       20260501.0      1.000000
25%       20260501.0    150.750000
50%       20260501.0    300.500000
75%       20260501.0    450.250000
max       20260501.0    600.000000

,Internal_Key,ISIN,RIC,Instrument_Name,Country,Currency,Exchange,Index Membership
count,600,600,600,600,600,600,600,573
unique,600,600,600,600,17,8,16,3
top,546078,NL0010273215,ASML.AS,ASML HLDG,GB,EUR,London SE,Large
freq,1,1,1,1,128,297,127,200

---

---

### **2.3 Analytic Approach**

#### **2.3.1 Causal Inference**

1. Causal Graph

2. Backdoor Adjustment

**Justification:** We will model CEO turnover as a governance shock in a DAG and use backdoor adjustment to control for firm fundamentals that affect both turnover and pay. We will estimate the causal effect of turnover using pre/post (event‑study style) comparisons around the turnover year.

#### **2.3.2 Supervised Learning**

1. Linear / Ridge / Lasso Regression

2. Logistic Regression

3. Decision Tree / Random Forest

4. Gradient Boosting (XGBoost / LightGBM / sklearn GBM)

**Justification:** Supervised models will benchmark expected compensation conditional on firm and executive characteristics. Linear models provide interpretable baselines and covariate effects, while tree-based and boosting models capture nonlinearities/interactions for more accurate counterfactual pay predictions. We will use Optuna to tune boosting hyperparameters (e.g., depth, learning rate, subsampling) to avoid overfitting and compare against simpler baselines.

#### **2.3.3 Unsupervised Learning**

1. K-Means Clustering

2. Variational Autoencoder

**Justification:** Clustering will segment firms into comparable peer groups before causal estimation and highlight heterogeneous effects across turnover regimes. A VAE will learn low-dimensional representations of firm/executive profiles to detect anomalous pay structures and support exploratory subgroup analysis.

### **2.4 Evaluation Metric**

RMSE

**Justification: ...**

### **2.5 Research Work Plan**

| Step | Owner | Description |
|------|-------|-------------|
| 1 | Achmad | Data collection & merging from BoardEx/Compustat; define CEO turnover events |
| 2 | Kajetan | Data cleaning, missing-value strategy, currency/inflation adjustments |
| 3 | Achmad | EDA + descriptive stats; define pay dispersion metrics |
| 4 | Kajetan | Causal inference block (DAG, event-window design around turnover, ATE estimation) |
| 5 | Achmad | Supervised learning benchmark models + heterogeneity analysis |
| 6 | Kajetan | Unsupervised/generative clustering/embeddings; peer-group analysis |
| 7 | Achmad + Kajetan | Synthesis, robustness checks, and final write-up |

---

## **3. Data Understanding (Exploratory Data Analysis)**

### **3.1 Data Inspection and Descriptive Statistics**

**1. Individual Profile Employment**

In [20]:
df_emp.head(2)

,isin,datestartrole,directorname,companyname,dateendrole,brdposition,rolename,fulltextdescription,ned,primarykeyid,directorid,companyid,hocountryname
0,GB00B1YW4409,1900-01-01,John Yetman,3I GROUP PLC,9999-12-31,No,Executive,Investment Executive,No,1654504,8428,294,United Kingdom - England
1,GB00B1YW4409,2005-07-06,Rod Perry,3I GROUP PLC,9999-12-31,No,Consultant,Also Head of International Advisory Board of V...,No,2003633,11777,294,United Kingdom - England

| Column | Description |
|---|---|
| `isin` | International Securities Identification Number identifying the listed company/security. |
| `datestartrole` | Date when the individual started the reported role. |
| `directorname` | Name of the executive, director, or board member. |
| `companyname` | Name of the company where the individual holds or held the role. |
| `dateendrole` | Date when the role ended. Placeholder dates such as `9000-01-01` or `9999-12-31` indicate an ongoing or open-ended role. |
| `brdposition` | Indicates whether the role is a board position. Values are typically `Yes` or `No`. |
| `rolename` | Official title or position held by the individual, such as Group COO, Deputy Chair, or Independent Board Member. |
| `fulltextdescription` | Additional description or context about the role, if available. |
| `ned` | Indicates whether the individual is a non-executive director. Values are typically `Yes` or `No`. |
| `primarykeyid` | Unique identifier for the specific role/employment record. |
| `directorid` | Unique identifier for the individual executive or director. |
| `companyid` | Unique identifier for the company in the database. |
| `hocountryname` | Country of the company’s headquarters. |

In [21]:
display(df_emp.describe())
display(df_emp.describe(include="object"))

       primarykeyid    directorid     companyid
count  9.519700e+04  9.519700e+04  9.519700e+04
mean   1.086665e+07  1.605869e+06  3.494934e+05
std    4.892264e+06  8.766853e+05  7.973995e+05
min    2.190000e+02  3.600000e+01  2.940000e+02
25%    6.600024e+06  9.880770e+05  1.062700e+04
50%    1.142107e+07  1.600838e+06  2.435000e+04
75%    1.515448e+07  2.354550e+06  3.284700e+04
max    1.859297e+07  3.308284e+06  4.052924e+06

,isin,datestartrole,directorname,companyname,dateendrole,brdposition,rolename,fulltextdescription,ned,hocountryname
count,95197,95197,95197,95197,95197,95197,95197,55987,95197,95197
unique,569,5885,50631,587,4073,2,9222,44480,2,26
top,DE0005140008,1900-01-01,Doctor Roland Busch,DEUTSCHE BANK AG,9000-01-01,No,Executive,Also Member of the Executive Committee,No,France
freq,1481,8931,19,1481,19320,74617,5439,754,78780,17224

**Insights:**

-

-

**2. Individual Profile Details**

**3. Company Profile Details**

In [22]:
df_firm.head(2)

,isin,boardname,boardnameshort,hoaddress1,hoaddress2,hoaddress3,hoaddress4,hoaddress5,hocountryname,hotelnumber,...,successorcompanyid,ultimateparentcompanyid,boardid,ticker,countryofquote,primarystock,currency,mktcapitalisation,noemployees,revenue
0,NaN,1955 INVERSIONES SIMCAV SA,1955 INVERSIONES SIMCAV SA,NaN,NaN,NaN,NaN,NaN,Spain,NaN,...,NaN,NaN,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,FIRST ACTIVE PLC (De-listed 01/2004),FIRST ACTIVE PLC,NaN,NaN,NaN,NaN,NaN,Republic Of Ireland,NaN,...,783081.0,NaN,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**4. Annual Renumeration**

**5. Firms in Stoxx 600 Index**

In [23]:
df_sxxp

,Creation_Date,Internal_Key,ISIN,RIC,Instrument_Name,Country,Currency,Exchange,Index Membership,Rank (FINAL)
0,20260501,546078,NL0010273215,ASML.AS,ASML HLDG,NL,EUR,Euronext Amsterdam,Large,1
1,20260501,40054,GB0005405286,HSBA.L,HSBC,GB,GBP,London SE,Large,2
2,20260501,98952,GB0009895292,AZN.L,ASTRAZENECA,GB,GBP,London SE,Large,3
3,20260501,474577,CH0012032048,ROPC.S,ROCHE PS,CH,CHF,Six Swiss Exchange,Large,4
4,20260501,477408,CH0012005267,NOVN.S,NOVARTIS,CH,CHF,Six Swiss Exchange,Large,5
...,...,...,...,...,...,...,...,...,...,...
595,20260501,466514,FI0009002422,OUT1V.HE,OUTOKUMPU,FI,EUR,NASDAQ Helsinki,NaN,596
596,20260501,BE11G7,BE0974400328,AZE.BR,AZELIS GROUP,BE,EUR,Euronext Brussels,NaN,597
597,20260501,B1FW50,GB00B1FW5029,HOCM.L,HOCHSCHILD MINING,GB,GBP,London SE,Small,598
598,20260501,GB20F8,GB0006928617,UTG.L,UNITE GROUP PLC,GB,GBP,London SE,Small,599
599,20260501,GB8054,JE00BF4X3P53,JTC.L,JTC GROUP,GB,GBP,London SE,NaN,600

___

**DF_REMUN FROM COMPANY_ID**

**Obtain Stoxx600 ID from company profile details**

In [ ]:
conn.get_data(
    library="boardex",
    table="eur_company_profile_details"
)

Approximately 444958 rows in boardex.eur_company_profile_details.

,name,nullable,type,comment
0,boardname,True,VARCHAR(128),Full company name or abbreviation in the case ...
1,boardnameshort,True,VARCHAR(255),Full company name only
2,hoaddress1,True,VARCHAR(128),None
3,hoaddress2,True,VARCHAR(128),None
4,hoaddress3,True,VARCHAR(128),None
5,hoaddress4,True,VARCHAR(64),None
6,hoaddress5,True,VARCHAR(64),None
7,hocountryname,True,VARCHAR(255),None
8,hotelnumber,True,VARCHAR(50),None
9,hofaxnumber,True,VARCHAR(50),None
10,hourl,True,VARCHAR(255),None
11,financialurl,True,VARCHAR(255),None
12,companypolicy,True,VARCHAR(255),None
13,ccaddress1,True,VARCHAR(128),None
14,ccaddress2,True,VARCHAR(128),None
15,ccaddress3,True,VARCHAR(128),None
16,ccaddress4,True,VARCHAR(64),None
17,ccaddress5,True,VARCHAR(64),None
18,cccountryname,True,VARCHAR(255),None
19,cctelnumber,True,VARCHAR(50),None
20,ccfaxnumber,True,VARCHAR(50),None
21,cikcode,True,VARCHAR(10),None
22,sector,True,VARCHAR(100),None
23,index,True,VARCHAR(255),None
24,orgvisible,True,VARCHAR(3),None
25,orgtype,True,VARCHAR(100),None
26,previouscompanyid,True,VARCHAR(255),Previous ID of Company
27,successorcompanyid,True,VARCHAR(255),Successor ID of Company
28,ultimateparentcompanyid,True,VARCHAR(100),ID of the ultimate parent company if part of a...
29,boardid,True,DOUBLE PRECISION,None

In [36]:
isin_list = df_sxxp["ISIN"].dropna().unique().tolist()
isin_list

['NL0010273215',
 'GB0005405286',
 'GB0009895292',
 'CH0012032048',
 'CH0012005267',
 'CH0038863350',
 'GB00BP6MXD84',
 'DE0007236101',
 'FR0000120271',
 'FR0000121972',
 'ES0113900J37',
 'DE0007164600',
 'DE0008404005',
 'DE000ENER6Y0',
 'CH0012221716',
 'ES0144580Y14',
 'DK0060534915',
 'CH0244767585',
 'GB00B63H8491',
 'FR0000121014',
 'GB0007980591',
 'GB0002875804',
 'GB00B10RZP78',
 'ES0113211835',
 'FR0000120073',
 'NL0000235190',
 'FR0000073272',
 'IT0005239360',
 'DE0005557508',
 'FR0000131104',
 'GB0007188757',
 'GB00BN7SWP63',
 'FR0000120578',
 'IT0000072618',
 'FR0000120321',
 'CH0210483332',
 'CH0011075394',
 'GB00BDR05C01',
 'IT0003128367',
 'FR0000125486',
 'DE0006231004',
 'NL0011821202',
 'FR0000120628',
 'GB0002634946',
 'GB0031348658',
 'GB0008706128',
 'DE0008430026',
 'BE0974293251',
 'SE0015811963',
 'DE0007030009',
 'JE00B4T3BW64',
 'FI0009000681',
 'FR0000052292',
 'GB00B2B0DG97',
 'FR0000121667',
 'ES0148396007',
 'GB00BM8PJY71',
 'GB00B0SWJX34',
 'FI4000297767',
 'FR0000130809',
 'FR0010208488',
 'DE0005140008',
 'NL0013654783',
 'DE000BASF111',
 'DE0005810055',
 'DE0005552004',
 'SE0000115446',
 'IT0003132476',
 'GB00B1XZS820',
 'GB00BD6K4575',
 'FR0000120644',
 'DE000ENAG999',
 'DE0007037129',
 'CH0012214059',
 'IT0000062072',
 'SE0017486889',
 'NL0010832176',
 'DK0060079531',
 'CH0126881561',
 'NL0000334118',
 'FR0010307819',
 'GB0004082847',
 'FR0000125007',
 'ES0140609019',
 'GB0002374006',
 'IT0004176001',
 'SE0000667891',
 'DE000BAY0017',
 'GB0007908733',
 'CH0013841017',
 'GB00B24CGK77',
 'DE0007100000',
 'NL0011794037',
 'GB00BLGZ9862',
 'FR0000133308',
 'NL0011585146',
 'GB00BMX86B70',
 'GB0007099541',
 'SE0007100581',
 'CH0432492467',
 'NL0000226223',
 'NL0012969182',
 'CH1243598427',
 'SE0000108656',
 'GB00B1YW4409',
 'NO0010096985',
 'ES0118900010',
 'BE0003739530',
 'DK0010274414',
 'CH0014852781',
 'AT0000652011',
 'GB00B19NLV48',
 'CH1335392721',
 'SE0000242455',
 'GB0000536739',
 'DE000A1EWWW0',
 'SE0000148884',
 'DK0061539921',
 'GB00BH4HKS39',
 'ES0167050915',
 'ES0173516115',
 'CH0418792922',
 'BE0003565737',
 'DE000CBK1001',
 'GB0004544929',
 'FR0000124141',
 'SE0012853455',
 'DE0006047004',
 'CH0010645932',
 'DE000DTR0CK8',
 'FR0000121329',
 'GB00BPQY8M80',
 'ES0109067019',
 'FI0009003305',
 'DE0005190003',
 'NO0010161896',
 'FI0009013403',
 'LU1598757687',
 'IT0003856405',
 'FR001400AJ45',
 'CH0024608827',
 'IE00BF0L3536',
 'IT0005218752',
 'NL0015000IY2',
 'NL0010773842',
 'CH0030170408',
 'SE0015961909',
 'GB0004052071',
 'PLPKO0000016',
 'NL0000009165',
 'FR0000130577',
 'IE00BYTBXV33',
 'SE0007100599',
 'FR0000045072',
 'CH0008742519',
 'GB0032089863',
 'NL0012866412',
 'DK0060336014',
 'NL0011540547',
 'PLPKN0000018',
 'GB00BHJYC057',
 'CH0466642201',
 'IT0000066123',
 'DE0007664039',
 'FR0000125338',
 'NL0000009538',
 'NL0000009082',
 'FI0009003727',
 'CH0311864901',
 'SE0000112385',
 'ES0105046009',
 'DE0005785604',
 'DE000A1ML7J1',
 'ES0113860A34',
 'FR0000121485',
 'GB0000456144',
 'GB0030913577',
 'GB0005603997',
 'DE000A0D9PT0',
 'DE0008402215',
 'NL0000395903',
 'CH0002497458',
 'SE0015658109',
 'IE00BD1RP616',
 'SE0000695876',
 'DK0010272202',
 'IT0003242622',
 'GB00B082RF11',
 'CH0102484968',
 'ES0178430E18',
 'DE0006599905',
 'ES0105066007',
 'PTEDP0AM0009',
 'FR0000120503',
 'IT0005218380',
 'FR0014003TT8',
 'IT0003153415',
 'FI0009005987',
 'FR0000130452',
 'SE0009922164',
 'DE000SHL1006',
 'IT0000072170',
 'FI0009013296',
 'NL00150001Q9',
 'SE0017768716',
 'NO0003043309',
 'FR0000120693',
 'CH0025751329',
 'IE0004927939',
 'NO0005052605',
 'CH0024638196',
 'ES0130670112',
 'CH0008038389',
 'GB00BMJ6DW54',
 'IE0004906560',
 'GB0009223206',
 'IT0004965148',
 'GB00B39J2M42',
 'GB00B033F229',
 'NL0006294274',
 'AT0000BAWAG2',
 'FR0013326246',
 'CH1175448666',
 'BE0974264930',
 'GB0001826634',
 'CH0025238863',
 'NL0000009827',
 'FR0000120172',
 'DK0010181759',
 'CH0198251305',
 'GB00B02J6398',
 'IT0003796171',
 'DK0060094928',
 'CH0010570767',
 'SE0000667925',
 'GB00BL9YR756',
 'ES0177542018',
 'GB00B1FH8J72',
 'NO0010345853',
 'GB00B5ZN1N88',
 'DE000SYM9999',
 'PLKGHM000017',
 'SE0005190238',
 'GB00B8C3BL03',
 'NL0011872643',
 'DE0006048432',
 'FI0009014575',
 'FI0009007132',
 'PLPEKAO00016',
 'GB00B1WY2338',
 'SE0000872095',
 'CH0012549785',
 'FR0006174348',
 'ES0113679I37',
 'GB00B0744B38',
 'IT0004810054',
 'GB00BYQ0JC66',
 'NO0010063308',
 'LU0156801721',
 'CH1169360919',
 'NL0000303709',
 'AT0000743059',
 'FR0000120404',
 'NL0013267909',
 'DE0006602006',
 'PLPZU0000011',
 'GB0031638363',
 'NO0003054108',
 'GB00BGLP8L22',
 'FR0012757854',
 'PTGAL0AM0009',
 'SE0000113250',
 'DK0060448595',
 'FR0010451203',
 'PTBCP0AM0015',
 'NO0010208051',
 'SE0014781795',
 'DE0006070006',
 'GB0009465807',
 'SE0012673267',
 'GB0006776081',
 'GB0031274896',
 'NO0003733800',
 'CH0018294154',
 'FR0000121964',
 'CH1101098163',
 'FR0011726835',
 'GB00BKFB1C65',
 'SE0000107203',
 'GB00BGXQNP29',
 'FI0009014377',
 'IT0003497168',
 'GB0003718474',
 'DE0005785802',
 'NL0000008977',
 'DE000A1DAHH0',
 'SE0000163594',
 'ES0116870314',
 'NO0003053605',
 'SE0000108227',
 'GB0007669376',
 'BE0003822393',
 'DK0010244425',
 'SE0000114837',
 'SE0000106270',
 'LU0075646355',
 'FR0014000MR3',
 'DE0005439004',
 'GB00B2QPKJ12',
 'GB00BNR5MZ78',
 'DK0010287663',
 'GB00B019KW72',
 'DE000TLX1005',
 'PLLPP0000011',
 'FR0012333284',
 'IT0005211237',
 'DE000KBX1006',
 'GB0002405495',
 'GB0009697037',
 'DK0060636678',
 'DE0005200000',
 'FI0009007884',
 'NL0012059018',
 'GB00BYT1DJ19',
 'FR0000131906',
 'GB00BWFGQN14',
 'PLBZ00000044',
 'GB0006731235',
 'NL0015002MS2',
 'ES0125220311',
 'DE000A0D6554',
 'FR0010259150',
 'IT0005495657',
 'BE0003764785',
 'ES0173093024',
 'NL0012169213',
 'BE0003851681',
 'SE0015949201',
 'FR0010533075',
 'BMG4593F1389',
 'AT0000606306',
 'FR0000044448',
 'IT0005541336',
 'FR0010220475',
 'FI0009005870',
 'BE0003797140',
 'LU2237380790',
 'GB00B06QFB75',
 'FI0009005961',
 'FI0009000202',
 'CH0012255151',
 'PTJMT0AE0001',
 'ES0105025003',
 'IE0002424939',
 'GB0033195214',
 'NL0010801007',
 'IT0003828271',
 'SE0015988019',
 'DE0007165631',
 'DK0060854669',
 'FR0004125920',
 'DE000A0WMPJ6',
 'FR0014004L86',
 'SE0000112724',
 'DE000A12DM80',
 'NL0014559478',
 'CH0010675863',
 'GB00BYW0PQ60',
 'FR0010411983',
 'GB00BD3VFW73',
 'DE000ZAL1111',
 'DE0007500001',
 'CH0016440353',
 'DK0010311471',
 'GB0031743007',
 'AT0000937503',
 'GB0005576813',
 'SE0001515552',
 'DK0060252690',
 'GB00BVYVFW23',
 'DK0010307958',
 'SE0015949748',
 'FR0010908533',
 'GB00B4WFW713',
 'CH0023405456',
 'DE000PAH0038',
 'NL0000360618',
 'SE0015192067',
 'AT0000730007',
 'SE0000120669',
 'GB0000961622',
 'DE000HAG0005',
 'FR0012435121',
 'GB00BF4HYT85',
 'CH0319416936',
 'DE0006766504',
 'PLOPTTC00011',
 'DE000PAG9113',
 'DE000RENK730',
 'CH0360674466',
 'GB0001367019',
 'DE000A2E4K43',
 'CH0009002962',
 'DK0060542181',
 'DE000LEG1110',
 'NO0010582521',
 'GB00BF8Q6K64',
 'SE0014990966',
 'BMG3682E1921',
 'DE000EVNK013',
 'DE0008232125',
 'SE0011337708',
 'NO0010631567',
 'FR0013154002',
 'GB00B1KJJ408',
 'FR0013506730',
 'ES0118594417',
 'GB00BJFFLV09',
 'ES0127797019',
 'BE0974349814',
 'DK0061802139',
 'AT0000746409',
 'BE0003604155',
 'CH0012453913',
 'BE0003823409',
 'IT0004776628',
 'CH0435377954',
 'GB0000811801',
 'IT0003261697',
 'NO0010736879',
 'FR0013258662',
 'GB00BZ4BQC70',
 'SE0000375115',
 'GB00B17BBQ50',
 'ES0130960018',
 'BE0974464977',
 'FR0010313833',
 'SE0000379190',
 'LU2290522684',
 'NO0011202772',
 'CH0030380734',
 'IE0000669501',
 'GB0006825383',
 'DE0006452907',
 'GB00BG49KP99',
 'BE0974259880',
 'GB00BGDT3G23',
 'NO0010310956',
 'ES0124244E34',
 'SE0012454072',
 'CH0531751755',
 'NL0015435975',
 'IT0001233417',
 'SE0005127818',
 'IM00B5VQMV65',
 'GB00BVGBY890',
 'IT0001347308',
 'SE0000202624',
 'IL0011284465',
 'BE0003717312',
 'CH1169151003',
 'PLDINPL00011',
 'CH0008837566',
 'FR0000121220',
 'SE0000108847',
 'GB0033986497',
 'SE0017832488',
 'FR0000039299',
 'PLBRE0000012',
 'GB00BLJNXL82',
 'GB00B1CRLC47',
 'FR0013280286',
 'GB00B1VNSX38',
 'FR0000051807',
 'SE0016278196',
 'FR0013227113',
 'GB00B61TVQ02',
 'FR0010040865',
 'CH1386220409',
 'CH0014284498',
 'JE00BJ1DLW90',
 'GB0002318888',
 'JE00B8KF9B49',
 'CH0130293662',
 'BE0974320526',
 'IT0005482333',
 'GB0003096442',
 'DE0005470306',
 'CH0012138605',
 'JE00BRX98089',
 'GB0007973794',
 'FI4000074984',
 'DE0005909006',
 'IT0001031084',
 'IT0001250932',
 'DE000A0Z2ZZ5',
 'GB0008782301',
 'DE0007010803',
 'GB00BKDRYJ47',
 'NO0003055501',
 'GB00BVMN1558',
 'CH0014786500',
 'CH0225173167',
 'DE000KGX8881',
 'ES0180907000',
 'FR0000064578',
 'FI4000552526',
 'CH0011108872',
 'GB0031215220',
 'GB00BNNTLN49',
 'PLBSK0000017',
 'IT0001078911',
 'GB00BVFNZH21',
 'BE0003867844',
 'FR0010340141',
 'PLBNFTS00018',
 'NL0000852564',
 'DE000TUAG000',
 'DE000TUAG505',
 'CH0038388911',
 'SE0006993770',
 'SE0010100958',
 'IT0004764699',
 'GB00BYRJ5J14',
 'GB00BV9FP302',
 'DE0008303504',
 'NL0015073TS8',
 'IT0005366767',
 'GB0004300496',
 'NL0015000LU4',
 'ES0182870214',
 'NL0000379121',
 'DE0006969603',
 'JE00BMDZN391',
 'DE000FTG1111',
 'NO0003078800',
 'CH0011029946',
 'FR0013451333',
 'SE0014504817',
 'AT0000831706',
 'GB00BNHSJN34',
 'DK0010234467',
 'GB0004657408',
 'FR0013269123',
 'NO0006000900',
 'GB00BYT18307',
 'DE000A3E5D64',
 'FI0009000459',
 'DE000KSAG888',
 'ES0132105018',
 'GB0000904986',
 'PLALIOR00045',
 'CH0528751586',
 'DK0060257814',
 'IT0005278236',
 'GB00B0LCW083',
 'PLKETY000011',
 'NL0000302636',
 'DE000A2LQ884',
 'PLBIG0000016',
 'DE0005773303',
 'IT0004931058',
 'NL0006237562',
 'CH0360826991',
 'NO0013697029',
 'SE0009806607',
 'DK0060634707',
 'GB00BNTJ3546',
 'GB0008085614',
 'LU0088087324',
 'DK0060738599',
 'CH1176493729',
 'DK0010219153',
 'GB00BJVQC708',
 'ES0171996087',
 'SE0014960373',
 'NL0000337319',
 'NO0006390301',
 'DE0005158703',
 'NL0011821392',
 'CH0239229302',
 'GB0004270301',
 'ES0105777017',
 'AT0000969985',
 'PLSOFTB00016',
 'FR0013176526',
 'NL0009432491',
 'GB00B0WMWD03',
 'NO0010234552',
 'CH0126673539',
 'IT0003115950',
 'PLTAURN00011',
 'GB00B62G9D36',
 'NO0010209331',
 'CH0022268228',
 'FI0009002422',
 'BE0974400328',
 'GB00B1FW5029',
 'GB0006928617',
 'JE00BF4X3P53']

---

**Obtain Related Data based on on ISIN**

**1. Individual Profile Employment**

In [ ]:
isin_list = df_sxxp["ISIN"].dropna().unique().tolist()

chunks = []
chunk_size = 1000

for i in range(0, len(isin_list), chunk_size):
    isin_chunk = tuple(isin_list[i:i + chunk_size])

    temp = conn.raw_sql("""
        SELECT *
        FROM boardex.eur_wrds_dir_profile_emp
        WHERE isin IN %(isins)s
        ORDER BY companyname, rolename, datestartrole, directorname
    """, params={"isins": isin_chunk})

    chunks.append(temp)

df_emp = pd.concat(chunks, ignore_index=True)

In [24]:
isin_list = df_sxxp["ISIN"].dropna().unique().tolist()

chunks = []
chunk_size = 1000

for i in range(0, len(isin_list), chunk_size):
    isin_chunk = tuple(isin_list[i:i + chunk_size])

    temp = conn.raw_sql("""
        SELECT *
        FROM boardex.eur_wrds_dir_profile_emp
        WHERE isin IN %(isins)s
        ORDER BY companyname, rolename, datestartrole, directorname
    """, params={"isins": isin_chunk})

    chunks.append(temp)

df_emp = pd.concat(chunks, ignore_index=True)

In [25]:
df_emp.head()

,rowtype,directorname,companyname,datestartrole,dateendrole,brdposition,rolename,fulltextdescription,ned,leadershipteam,primarykeyid,directorid,companyid,datestartroleflag,dateendroleflag,hocountryname,sector,orgtype,isin
0,Listed Organisations,Manoj Jain,3I GROUP PLC,2011-03-01,2014-05-28,No,Accountant,Fund Accountant,No,No,15144705.0,2614052.0,294.0,20.0,15.0,United Kingdom - England,Private Equity,Quoted,GB00B1YW4409
1,Listed Organisations,Pascal Lebard,3I GROUP PLC,1988-01-02,1989-12-31,No,Accounting Manager,<NA>,No,No,1332399.0,30680.0,294.0,30.0,25.0,United Kingdom - England,Private Equity,Quoted,GB00B1YW4409
2,Listed Organisations,Frédéric Vern,3I GROUP PLC,1900-01-01,9999-12-31,No,Advisor,<NA>,No,No,10093877.0,1915872.0,294.0,75.0,80.0,United Kingdom - England,Private Equity,Quoted,GB00B1YW4409
3,Listed Organisations,Kimmo Korpela,3I GROUP PLC,1900-01-01,9999-12-31,No,Advisor,Also Associate Director of 3i Sweden,No,No,5279095.0,1192043.0,294.0,75.0,80.0,United Kingdom - England,Private Equity,Quoted,GB00B1YW4409
4,Listed Organisations,Marcel van Poecke,3I GROUP PLC,1900-01-01,9999-12-31,No,Advisor,Benelux,No,No,2630695.0,330763.0,294.0,75.0,80.0,United Kingdom - England,Private Equity,Quoted,GB00B1YW4409

568

**2. Individual Profile Details**

In [26]:
directorid_list = df_emp["directorid"].dropna().unique().tolist()

chunks = []
chunk_size = 1000

for i in range(0, len(directorid_list), chunk_size):
    directorid_chunk = tuple(directorid_list[i:i + chunk_size])

    temp = conn.raw_sql("""
        SELECT directorname, title, forename1, surname, gender, directorid, primaryroleid
        FROM boardex.eur_dir_profile_details
        WHERE directorid IN %(directorids)s
        ORDER BY directorname ASC
    """, params={"directorids": directorid_chunk})

    chunks.append(temp)

df_exec = pd.concat(chunks, ignore_index=True)

In [27]:
df_exec.head(3)

,directorname,title,forename1,surname,gender,directorid,primaryroleid
0,Aaron Church,Mr,Aaron,Church,M,1348931.0,13060661.0
1,Admiral Rene Van Der Bruggen,Admiral,René,van der Bruggen,M,327778.0,4641608.0
2,Adriano Bandera,Mr,Adriano,Bandera,M,602849.0,4378308.0

In [28]:
df_exec_emp = df_exec.merge(df_emp, how = 'inner')[['directorid', 'directorname', 'title', 'companyname', 'companyid', 'rolename', 'datestartrole', 'dateendrole']]
df_exec_emp

,directorid,directorname,title,companyname,companyid,rolename,datestartrole,dateendrole
0,1348931.0,Aaron Church,Mr,3I GROUP PLC,294.0,Director - Infrastructure,2013-07-01,2022-04-28
1,1348931.0,Aaron Church,Mr,3I GROUP PLC,294.0,Partner,2022-04-01,9000-01-01
2,327778.0,Admiral Rene Van Der Bruggen,Admiral,AALBERTS NV (Aalberts Industries NV prior to 0...,384.0,Independent Board Member,2011-04-21,2014-04-22
3,602849.0,Adriano Bandera,Mr,A2A SPA,953.0,Director - SD,2008-02-22,2012-05-29
4,1520966.0,Adrian Yurkwich,Mr,3I GROUP PLC,294.0,Investment Executive,1995-03-01,1998-10-28
...,...,...,...,...,...,...,...,...
141817,601419.0,Yngve Bärgård,Mr,WARTSILA OYJ ABP,33085.0,Vice President - Supply,2005-08-01,2013-12-28
141818,1055598.0,Yves Bonte,Mr,YARA INTERNATIONAL ASA,500428.0,Executive VP,2010-01-01,2019-01-01
141819,1055598.0,Yves Bonte,Mr,YARA INTERNATIONAL ASA,500428.0,Executive VP - Business,2019-01-01,2020-02-28
141820,1541272.0,Yvonne Jamal,Ms,ZALANDO SE,2154485.0,Alternate Employee Representative,2015-06-02,2016-12-28
141821,3034780.0,Zbigniew Laskowski,Mr,ZALANDO SE,2154485.0,Employee Representative,2025-05-27,9000-01-01

In [29]:
# --- 1.2  Identify CEO roles within STOXX 600 firms ---
CEO_PATTERN = r"chief executive|(?<!\w)ceo(?!\w)|managing director"
df_exec_emp["is_ceo"] = df_exec_emp["rolename"].str.lower().str.contains(CEO_PATTERN, na=False, regex=True)
df_ceo_emp = df_exec_emp[df_exec_emp["is_ceo"]].copy()

df_ceo_emp = df_ceo_emp.sort_values(by=['companyname', 'rolename', 'datestartrole'])

print(f"CEO role-records in STOXX 600 firms: {len(df_ceo_emp)}")
df_ceo_emp["rolename"].value_counts().head(10)

CEO role-records in STOXX 600 firms: 8044

rolename
Division CEO                       2690
CEO                                 727
Regional CEO                        599
President/CEO                       435
Chairman/CEO                        415
Division Chairman/Division CEO      256
Deputy CEO                          218
Division President/Division CEO     179
Division President/CEO              145
Division Deputy CEO                 124
Name: count, dtype: Int64

In [30]:
df_ceo_emp.head(3)

,directorid,directorname,title,companyname,companyid,rolename,datestartrole,dateendrole,is_ceo
2276,342366.0,Simon Borrows,Mr,3I GROUP PLC,294.0,CEO,2012-05-17,9000-01-01,True
1535,1297838.0,Maite Ballester Fornés,Ms,3I GROUP PLC,294.0,Regional CEO,2008-01-01,2014-03-28,True
15513,534736.0,Søren Skou,Mr,A.P. MOLLER-MAERSK A/S,250471.0,CEO,2016-07-01,2023-01-01,True

In [31]:
df_ceo_only = df_ceo_emp[df_ceo_emp["rolename"] == "CEO"]
df_ceo_only

,directorid,directorname,title,companyname,companyid,rolename,datestartrole,dateendrole,is_ceo
2276,342366.0,Simon Borrows,Mr,3I GROUP PLC,294.0,CEO,2012-05-17,9000-01-01,True
15513,534736.0,Søren Skou,Mr,A.P. MOLLER-MAERSK A/S,250471.0,CEO,2016-07-01,2023-01-01,True
15693,1526460.0,Vincent Clerc,Mr,A.P. MOLLER-MAERSK A/S,250471.0,CEO,2023-01-01,9000-01-01,True
1514,1587233.0,Luca Camerano,Mr,A2A SPA,953.0,CEO,2014-06-16,2017-07-11,True
2560,654106.0,Wim Pelsma,Mr,AALBERTS NV (Aalberts Industries NV prior to 0...,384.0,CEO,2012-04-26,2023-09-07,True
...,...,...,...,...,...,...,...,...,...
114595,8797.0,Peter Eckert,Mr,ZURICH INSURANCE GROUP AG,34200.0,CEO,2000-10-01,2001-07-28,True
141624,8796.0,Rolf Hüppi,Mr,ZURICH INSURANCE GROUP AG,34200.0,CEO,2002-05-16,2002-05-17,True
126772,31847.0,Martin Senn,Mr,ZURICH INSURANCE GROUP AG,34200.0,CEO,2010-01-01,2012-06-04,True
126773,31847.0,Martin Senn,Mr,ZURICH INSURANCE GROUP AG,34200.0,CEO,2012-09-01,2015-12-01,True
140673,2755328.0,Carsten Christoffersen,Mr,ZURICH INSURANCE GROUP AG,34200.0,CEO,2018-01-01,2023-12-28,True

**4. Individual Annual Remuneration**

In [32]:
directorid_list = df_exec["directorid"].dropna().astype(int).unique().tolist()

chunks = []
chunk_size = 1000

for i in range(0, len(directorid_list), chunk_size):
    directorid_chunk = tuple(directorid_list[i:i + chunk_size])

    temp = conn.raw_sql("""
        SELECT 
            boardname,
            boardid,
            directorname,
            directorid,
            rolename,
            rolestatus,
            remchgelast,
            currency,
            salary,
            bonus,
            totalcompensation,
            annualreportdate
        FROM boardex.eur_dir_standard_remun
        WHERE directorid IN %(directorids)s
        ORDER BY boardname, directorname, annualreportdate ASC
    """, params={"directorids": directorid_chunk})

    chunks.append(temp)

df_remun = pd.concat(chunks, ignore_index=True) if chunks else pd.DataFrame()

In [39]:
df_remun_test = df_remun.sort_values(
    by=(['boardname', 'directorname', 'annualreportdate']),
    ascending=True
)

In [59]:
df_remun_test

,boardname,boardid,directorname,directorid,rolename,rolestatus,remchgelast,currency,salary,bonus,totalcompensation,annualreportdate
116460,029 GROUP SE (Mendarion SE prior to 08/2022),3593784.0,Leon Sander,2872572.0,Board Member - SD,Leon Sander has changed role on 01 Jul 2024,<NA>,USD,<NA>,<NA>,<NA>,2024-12-01
116461,029 GROUP SE (Mendarion SE prior to 08/2022),3593784.0,Leon Sander,2872572.0,MD,Leon Sander has changed role on 01 Jul 2024,<NA>,USD,<NA>,<NA>,<NA>,2024-12-01
116462,029 GROUP SE (Mendarion SE prior to 08/2022),3593784.0,Leon Sander,2872572.0,MD,Leon Sander joined this role on 01 Jul 2024,<NA>,USD,<NA>,<NA>,<NA>,<NA>
203335,1&1 AG (1&1 Drillisch AG prior to 06/2021),9638.0,Christine Schöneweis,2617542.0,Independent Board Member,Christine Schöneweis joined this role on 16 Ma...,<NA>,USD,<NA>,<NA>,<NA>,2023-12-01
203336,1&1 AG (1&1 Drillisch AG prior to 06/2021),9638.0,Christine Schöneweis,2617542.0,Independent Board Member,Christine Schöneweis joined this role on 16 Ma...,<NA>,USD,<NA>,<NA>,<NA>,2024-12-01
...,...,...,...,...,...,...,...,...,...,...,...,...
35023,Żabka Polska Sp Zoo,2228028.0,Tomasz Suchański,1851690.0,President/CEO,Tomasz Suchański joined this role on 01 Mar 2016,<NA>,USD,<NA>,<NA>,<NA>,2020-12-01
35024,Żabka Polska Sp Zoo,2228028.0,Tomasz Suchański,1851690.0,President/CEO,Tomasz Suchański joined this role on 01 Mar 2016,<NA>,USD,<NA>,<NA>,<NA>,2021-12-01
35025,Żabka Polska Sp Zoo,2228028.0,Tomasz Suchański,1851690.0,President/CEO,Tomasz Suchański joined this role on 01 Mar 2016,<NA>,USD,<NA>,<NA>,<NA>,2022-12-01
35026,Żabka Polska Sp Zoo,2228028.0,Tomasz Suchański,1851690.0,President/CEO,Tomasz Suchański joined this role on 01 Mar 2016,<NA>,USD,<NA>,<NA>,<NA>,2023-12-01
35027,Żabka Polska Sp Zoo,2228028.0,Tomasz Suchański,1851690.0,President,Tomasz Suchański has changed role on 01 Jun 2025,<NA>,USD,<NA>,<NA>,<NA>,<NA>

In [46]:
df_remun_test.annualreportdate.isna().sum()

np.int64(16657)

In [57]:
df_remun_test.totalcompensation.isna().sum()

np.int64(209303)

In [49]:
CEO_PATTERN = r"chief executive|(?<!\w)ceo(?!\w)|managing director"

In [54]:
df_remun_test_ceo = df_remun_test[df_remun_test["rolename"].str.lower().str.contains(CEO_PATTERN, na=False, regex=True)]
df_remun_test_ceo

,boardname,boardid,directorname,directorid,rolename,rolestatus,remchgelast,currency,salary,bonus,totalcompensation,annualreportdate
112054,1&1 AG (1&1 Drillisch AG prior to 06/2021),9638.0,Ralph Dommermuth,545942.0,CEO,Ralph Dommermuth joined this role on 01 Jan 2018,<NA>,USD,<NA>,<NA>,<NA>,2018-12-01
112055,1&1 AG (1&1 Drillisch AG prior to 06/2021),9638.0,Ralph Dommermuth,545942.0,CEO,Ralph Dommermuth joined this role on 01 Jan 2018,<NA>,USD,<NA>,<NA>,<NA>,2019-12-01
112056,1&1 AG (1&1 Drillisch AG prior to 06/2021),9638.0,Ralph Dommermuth,545942.0,CEO,Ralph Dommermuth joined this role on 01 Jan 2018,<NA>,USD,<NA>,<NA>,<NA>,2020-12-01
112057,1&1 AG (1&1 Drillisch AG prior to 06/2021),9638.0,Ralph Dommermuth,545942.0,CEO,Ralph Dommermuth joined this role on 01 Jan 2018,<NA>,USD,<NA>,<NA>,<NA>,2021-12-01
112058,1&1 AG (1&1 Drillisch AG prior to 06/2021),9638.0,Ralph Dommermuth,545942.0,CEO,Ralph Dommermuth joined this role on 01 Jan 2018,<NA>,USD,<NA>,<NA>,<NA>,2022-12-01
...,...,...,...,...,...,...,...,...,...,...,...,...
35022,Żabka Polska Sp Zoo,2228028.0,Tomasz Suchański,1851690.0,President/CEO,Tomasz Suchański joined this role on 01 Mar 2016,<NA>,USD,<NA>,<NA>,<NA>,2019-12-01
35023,Żabka Polska Sp Zoo,2228028.0,Tomasz Suchański,1851690.0,President/CEO,Tomasz Suchański joined this role on 01 Mar 2016,<NA>,USD,<NA>,<NA>,<NA>,2020-12-01
35024,Żabka Polska Sp Zoo,2228028.0,Tomasz Suchański,1851690.0,President/CEO,Tomasz Suchański joined this role on 01 Mar 2016,<NA>,USD,<NA>,<NA>,<NA>,2021-12-01
35025,Żabka Polska Sp Zoo,2228028.0,Tomasz Suchański,1851690.0,President/CEO,Tomasz Suchański joined this role on 01 Mar 2016,<NA>,USD,<NA>,<NA>,<NA>,2022-12-01
35026,Żabka Polska Sp Zoo,2228028.0,Tomasz Suchański,1851690.0,President/CEO,Tomasz Suchański joined this role on 01 Mar 2016,<NA>,USD,<NA>,<NA>,<NA>,2023-12-01

In [75]:
df_remun_new = df_remun_test[(df_remun_test["totalcompensation"] > 0) & df_remun_test['annualreportdate'].notnull()].drop_duplicates()
df_remun_new

,boardname,boardid,directorname,directorid,rolename,rolestatus,remchgelast,currency,salary,bonus,totalcompensation,annualreportdate
2,3I INFRASTRUCTURE PLC (3i Infrastructure Ltd p...,932863.0,Jenny Dunstan,1126372.0,NED,Jenny Dunstan joined this role on 20 Jul 2023,<NA>,USD,44.0,<NA>,44.0,2024-03-01
3,3I INFRASTRUCTURE PLC (3i Infrastructure Ltd p...,932863.0,Jenny Dunstan,1126372.0,NED,Jenny Dunstan joined this role on 20 Jul 2023,0.49,USD,67.0,<NA>,67.0,2025-03-01
120557,3I INFRASTRUCTURE PLC (3i Infrastructure Ltd p...,932863.0,Peter Wagner,2257.0,Independent NED,Peter Wagner joined this role on 13 Mar 2007,<NA>,USD,209.0,<NA>,209.0,2008-03-01
120558,3I INFRASTRUCTURE PLC (3i Infrastructure Ltd p...,932863.0,Peter Wagner,2257.0,Independent NED,Peter Wagner joined this role on 13 Mar 2007,-0.32,USD,103.0,<NA>,103.0,2009-03-01
196937,3I INFRASTRUCTURE PLC (3i Infrastructure Ltd p...,932863.0,Richard Laing,26240.0,Chairman (Independent NED),Richard Laing joined this role on 01 Jan 2016,<NA>,USD,50.0,<NA>,50.0,2016-03-01
...,...,...,...,...,...,...,...,...,...,...,...,...
7085,ZURICH INSURANCE GROUP AG,34200.0,Tom de Swaan,15011.0,Independent Chairman,Tom de Swaan has changed role on 11 Sep 2013,<NA>,USD,613.0,<NA>,613.0,2013-12-01
7086,ZURICH INSURANCE GROUP AG,34200.0,Tom de Swaan,15011.0,Independent Chairman,Tom de Swaan joined this role on 11 Sep 2013,0.75,USD,1011.0,<NA>,1011.0,2014-12-01
7088,ZURICH INSURANCE GROUP AG,34200.0,Tom de Swaan,15011.0,Chairman/Interim CEO,Tom de Swaan has changed role on 01 Dec 2015,<NA>,USD,738.0,<NA>,738.0,2015-12-01
7089,ZURICH INSURANCE GROUP AG,34200.0,Tom de Swaan,15011.0,Independent Chairman,Tom de Swaan has changed role on 07 Mar 2016,<NA>,USD,736.0,<NA>,736.0,2016-12-01
7091,ZURICH INSURANCE GROUP AG,34200.0,Tom de Swaan,15011.0,Independent Chairman,Tom de Swaan joined this role on 07 Mar 2016,-0.01,USD,797.0,<NA>,797.0,2017-12-01

In [81]:
df_remun_new.boardname.unique()

<StringArray>
[                                                           '3I INFRASTRUCTURE PLC (3i Infrastructure Ltd prior to 07/2008)',
                                                                                'A&D PHARMA HOLDINGS NV (De-listed 03/2011)',
                                                                       'AARE-TESSIN AG FUR ELEKTRIZITAT (De-listed 06/2008)',
                                                                                                                   'ABB LTD',
                                             'ABERDEEN ASIAN INCOME FUND LTD (Abrdn Asian Income Fund Ltd prior to 06/2025)',
 'ABERDEEN FRONTIER MARKETS INVESTMENT COMPANY LTD (Advance Frontier Markets Fund Ltd prior to 04/2016) (De-listed 08/2020)',
                                                                                   'ABN AMRO HOLDING NV (De-listed 04/2008)',
       'ABRDN LATIN AMERICAN INCOME FUND LTD (Aberdeen Latin American Income Fund Ltd prior to 01/2022) (De-listed 06/2023)',
                                                                             'ABSOLUTE RETURN TRUST LTD (De-listed 12/2013)',
                                                                                       'ACCELL GROUP NV (De-listed 08/2022)',
 ...
                                                                                           'XLMEDIA PLC (De-listed 06/2025)',
                                                  'XPONCARD GROUP AB (Exponcard Group prior to 05/2001) (De-listed 06/2008)',
                                                                                           'XSTRATA PLC (De-listed 05/2013)',
                                                                                     'YATRA CAPITAL LTD (De-listed 05/2022)',
                                                                                                           'YELLOW CAKE PLC',
                                                                                    'YEW GROVE REIT PLC (De-listed 02/2022)',
                                                                                                                'ZALANDO SE',
                                                                                            'ZAMANO PLC (De-listed 09/2018)',
                                                                              'ZEAL NETWORK SE (Tipp24 SE prior to 11/2014)',
                                                                                                 'ZURICH INSURANCE GROUP AG']
Length: 654, dtype: string

In [77]:
df_remun_new.head()

,boardname,boardid,directorname,directorid,rolename,rolestatus,remchgelast,currency,salary,bonus,totalcompensation,annualreportdate
2,3I INFRASTRUCTURE PLC (3i Infrastructure Ltd p...,932863.0,Jenny Dunstan,1126372.0,NED,Jenny Dunstan joined this role on 20 Jul 2023,<NA>,USD,44.0,<NA>,44.0,2024-03-01
3,3I INFRASTRUCTURE PLC (3i Infrastructure Ltd p...,932863.0,Jenny Dunstan,1126372.0,NED,Jenny Dunstan joined this role on 20 Jul 2023,0.49,USD,67.0,<NA>,67.0,2025-03-01
120557,3I INFRASTRUCTURE PLC (3i Infrastructure Ltd p...,932863.0,Peter Wagner,2257.0,Independent NED,Peter Wagner joined this role on 13 Mar 2007,<NA>,USD,209.0,<NA>,209.0,2008-03-01
120558,3I INFRASTRUCTURE PLC (3i Infrastructure Ltd p...,932863.0,Peter Wagner,2257.0,Independent NED,Peter Wagner joined this role on 13 Mar 2007,-0.32,USD,103.0,<NA>,103.0,2009-03-01
196937,3I INFRASTRUCTURE PLC (3i Infrastructure Ltd p...,932863.0,Richard Laing,26240.0,Chairman (Independent NED),Richard Laing joined this role on 01 Jan 2016,<NA>,USD,50.0,<NA>,50.0,2016-03-01

---

**DF_REMUN FROM COMPANY_ID**

**Obtain Stoxx600 ID from company profile details**

In [26]:
conn.list_tables(library='boardex_eur')

['eur_board_characteristics',
 'eur_board_dir_announcements',
 'eur_board_dir_committees',
 'eur_board_education_assoc',
 'eur_board_listed_assoc',
 'eur_board_nfp_assoc',
 'eur_board_other_assoc',
 'eur_board_unlisted_assoc',
 'eur_company_profile_advisors',
 'eur_company_profile_details',
 'eur_company_profile_market_cap',
 'eur_company_profile_sr_mgrs',
 'eur_company_profile_stocks',
 'eur_dir_characteristics',
 'eur_dir_education_assoc',
 'eur_dir_listed_assoc',
 'eur_dir_nfp_assoc',
 'eur_dir_other_assoc',
 'eur_dir_profile_achievements',
 'eur_dir_profile_details',
 'eur_dir_profile_education',
 'eur_dir_profile_emp',
 'eur_dir_profile_other_activ',
 'eur_dir_standard_remun',
 'eur_dir_unlisted_assoc',
 'eur_lookupcompany',
 'eur_lookuproles',
 'eur_lookupsalutations',
 'eur_ltip_compensation',
 'eur_ltip_wealth',
 'eur_options_compensation',
 'eur_options_wealth',
 'eur_wrds_company_dir_names',
 'eur_wrds_company_names',
 'eur_wrds_company_networks',
 'eur_wrds_company_profile',
 'eur_wrds_company_region',
 'eur_wrds_dir_profile_all',
 'eur_wrds_dir_profile_emp',
 'eur_wrds_individual_networks',
 'eur_wrds_org_composition',
 'eur_wrds_org_summary']

In [29]:
# Extract first 5 obs from comp.company

company = conn.get_table(library='boardex_eur', table='eur_company_profile_details', obs=5)
company.columns

Index(['boardname', 'boardnameshort', 'hoaddress1', 'hoaddress2', 'hoaddress3',
       'hoaddress4', 'hoaddress5', 'hocountryname', 'hotelnumber',
       'hofaxnumber', 'hourl', 'financialurl', 'companypolicy', 'ccaddress1',
       'ccaddress2', 'ccaddress3', 'ccaddress4', 'ccaddress5', 'cccountryname',
       'cctelnumber', 'ccfaxnumber', 'cikcode', 'sector', 'index',
       'orgvisible', 'orgtype', 'previouscompanyid', 'successorcompanyid',
       'ultimateparentcompanyid', 'boardid'],
      dtype='object')

In [ ]:
# Extract first 5 obs from comp.company

stock = conn.get_table(library='boardex_eur', table='eur_company_profile_stocks', obs=5)
stock.columns

Index(['boardname', 'ticker', 'isin', 'orgvisible', 'countryofquote',
       'primarystock', 'boardid'],
      dtype='object')

In [31]:
stock.head()

,boardname,ticker,isin,orgvisible,countryofquote,primarystock,boardid
0,THREADNEEDLE UK SELECT TRUST LTD (UK Select Tr...,UKT,GB0004618236,Yes,ENGLAND AND WALES,Yes,296.0
1,3U HOLDING AG (3U Telecom AG prior to 11/2007),UUU,DE0005167902,Yes,GERMANY,Yes,304.0
2,CURATIS HOLDING AG (Kinarus Therapeutics Holdi...,CURN,CH1330780979,Yes,SWITZERLAND,Yes,310.0
3,CURATIS HOLDING AG (Kinarus Therapeutics Holdi...,KNRS,CH0009115129,Yes,SWITZERLAND,No,310.0
4,ANOVO SA (A Novo prior to 06/2008) (De-listed ...,NOV,FR0010698217,Yes,FRANCE,Yes,352.0

In [38]:
isin_list = df_sxxp["ISIN"].dropna().unique().tolist()

chunks = []
chunk_size = 1000

for i in range(0, len(isin_list), chunk_size):
    isin_chunk = tuple(isin_list[i:i + chunk_size])

    temp = conn.raw_sql("""
        SELECT *
        FROM boardex_eur.eur_company_profile_stocks
        WHERE isin IN %(isins)s
    """, params={"isins": isin_chunk})

    chunks.append(temp)

df_comp = pd.concat(chunks, ignore_index=True)

In [39]:
df_comp.head()

,boardname,ticker,isin,orgvisible,countryofquote,primarystock,boardid
0,AALBERTS NV (Aalberts Industries NV prior to 0...,AALB,NL0000852564,Yes,NETHERLANDS,Yes,384.0
1,ABB LTD,ABB,CH0012221716,Yes,SWEDEN,No,422.0
2,ABB LTD,ABBN,CH0012221716,Yes,SWITZERLAND,Yes,422.0
3,ACCIONA SA,ANA,ES0125220311,Yes,SPAIN,Yes,595.0
4,ACCOR SA,AC,FR0000120404,Yes,FRANCE,Yes,598.0

In [40]:
len(df_comp)

491

In [ ]:
directorid_list = df_exec["directorid"].dropna().astype(int).unique().tolist()

chunks = []
chunk_size = 1000

for i in range(0, len(directorid_list), chunk_size):
    directorid_chunk = tuple(directorid_list[i:i + chunk_size])

    temp = conn.raw_sql("""
        SELECT 
            boardname,
            boardid,
            directorname,
            directorid,
            rolename,
            rolestatus,
            remchgelast,
            currency,
            salary,
            bonus,
            totalcompensation,
            annualreportdate
        FROM boardex.eur_dir_standard_remun
        WHERE directorid IN %(directorids)s
        ORDER BY boardname, directorname, annualreportdate ASC
    """, params={"directorids": directorid_chunk})

    chunks.append(temp)

df_remun = pd.concat(chunks, ignore_index=True) if chunks else pd.DataFrame()

---

In [70]:
df_final = df_remun_test_ceo[
    df_remun_test_ceo["totalcompensation"] > 0
].drop_duplicates()
df_final

,boardname,boardid,directorname,directorid,rolename,rolestatus,remchgelast,currency,salary,bonus,totalcompensation,annualreportdate
76548,A&D PHARMA HOLDINGS NV (De-listed 03/2011),1055962.0,Dragos Dinu,620369.0,CEO,Dragos Dinu joined this role on 24 Oct 2006,<NA>,USD,460.0,<NA>,460.0,2007-12-01
1026,ABB LTD,422.0,Doctor Ulrich Spiesshofer,486454.0,President/CEO,Doctor Ulrich Spiesshofer has changed role on ...,<NA>,USD,1236.0,1506.0,2742.0,2013-12-01
1027,ABB LTD,422.0,Doctor Ulrich Spiesshofer,486454.0,President/CEO,Doctor Ulrich Spiesshofer joined this role on ...,-0.01,USD,1618.0,2083.0,3701.0,2014-12-01
1028,ABB LTD,422.0,Doctor Ulrich Spiesshofer,486454.0,President/CEO,Doctor Ulrich Spiesshofer joined this role on ...,0.35,USD,1619.0,2573.0,4192.0,2015-12-01
1053,ABB LTD,422.0,Fred Kindle,4611.0,CEO Designate,Fred Kindle joined this role on 01 Sep 2004,<NA>,USD,351.0,<NA>,351.0,2004-12-01
...,...,...,...,...,...,...,...,...,...,...,...,...
276707,ZALANDO SE,2154485.0,Robert Gentz,1461707.0,Co-CEO,Robert Gentz joined this role in 2017,208.78,USD,103.0,<NA>,103.0,2023-12-01
276708,ZALANDO SE,2154485.0,Robert Gentz,1461707.0,Co-CEO,Robert Gentz joined this role in 2017,-0.86,USD,404.0,<NA>,404.0,2024-12-01
276716,ZALANDO SE,2154485.0,Rubin Ritter,1461711.0,Co-CEO,Rubin Ritter joined this role in 2017,<NA>,USD,73.0,<NA>,73.0,2019-12-01
276717,ZALANDO SE,2154485.0,Rubin Ritter,1461711.0,Co-CEO,Rubin Ritter joined this role in 2017,0.06,USD,79.0,<NA>,79.0,2020-12-01
7088,ZURICH INSURANCE GROUP AG,34200.0,Tom de Swaan,15011.0,Chairman/Interim CEO,Tom de Swaan has changed role on 01 Dec 2015,<NA>,USD,738.0,<NA>,738.0,2015-12-01

In [73]:
df_final.head(50)

,boardname,boardid,directorname,directorid,rolename,rolestatus,remchgelast,currency,salary,bonus,totalcompensation,annualreportdate
76548,A&D PHARMA HOLDINGS NV (De-listed 03/2011),1055962.0,Dragos Dinu,620369.0,CEO,Dragos Dinu joined this role on 24 Oct 2006,<NA>,USD,460.0,<NA>,460.0,2007-12-01
1026,ABB LTD,422.0,Doctor Ulrich Spiesshofer,486454.0,President/CEO,Doctor Ulrich Spiesshofer has changed role on ...,<NA>,USD,1236.0,1506.0,2742.0,2013-12-01
1027,ABB LTD,422.0,Doctor Ulrich Spiesshofer,486454.0,President/CEO,Doctor Ulrich Spiesshofer joined this role on ...,-0.01,USD,1618.0,2083.0,3701.0,2014-12-01
1028,ABB LTD,422.0,Doctor Ulrich Spiesshofer,486454.0,President/CEO,Doctor Ulrich Spiesshofer joined this role on ...,0.35,USD,1619.0,2573.0,4192.0,2015-12-01
1053,ABB LTD,422.0,Fred Kindle,4611.0,CEO Designate,Fred Kindle joined this role on 01 Sep 2004,<NA>,USD,351.0,<NA>,351.0,2004-12-01
1054,ABB LTD,422.0,Fred Kindle,4611.0,President/CEO,Fred Kindle has changed role on 01 Jan 2005,<NA>,USD,993.0,306.0,1299.0,2005-12-01
1055,ABB LTD,422.0,Fred Kindle,4611.0,President/CEO,Fred Kindle joined this role on 01 Jan 2005,0.14,USD,1149.0,1540.0,2689.0,2006-12-01
1056,ABB LTD,422.0,Fred Kindle,4611.0,President/CEO,Fred Kindle joined this role on 01 Jan 2005,0.71,USD,1313.0,1746.0,3059.0,2007-12-01
1154,ABB LTD,422.0,Juergen Dormann,11152.0,Chairman/President/CEO,Juergen Dormann has changed role on 05 Sep 2002,<NA>,USD,1419.0,<NA>,1419.0,2002-12-01
1156,ABB LTD,422.0,Juergen Dormann,11152.0,Chairman/President/CEO,Juergen Dormann joined this role on 05 Sep 2002,0.58,USD,2414.0,<NA>,2414.0,2003-12-01
1158,ABB LTD,422.0,Juergen Dormann,11152.0,Chairman/President/CEO,Juergen Dormann joined this role on 05 Sep 2002,0.13,USD,2734.0,648.0,3383.0,2004-12-01
1144,ABB LTD,422.0,Jörgen Centerman,14884.0,President/CEO,Jörgen Centerman has changed role on 31 Dec 2000,<NA>,USD,894.0,894.0,1787.0,2001-12-01
1243,ABB LTD,422.0,Peter Voser,25679.0,Chairman/Interim CEO,Peter Voser has changed role on 17 Apr 2019,<NA>,USD,1227.0,1841.0,3068.0,2019-12-01
97931,ACCENTURE PLC (Accenture Ltd prior to 09/2009),573.0,Karl-Heinz Flöther,142129.0,Division Group Chief Executive,Karl-Heinz Flöther joined this role in Feb 2003,<NA>,USD,2063.0,192.0,2255.0,2005-08-01
97932,ACCENTURE PLC (Accenture Ltd prior to 09/2009),573.0,Karl-Heinz Flöther,142129.0,Division Group Chief Executive,Karl-Heinz Flöther joined this role in Feb 2003,0.25,USD,3782.0,186.0,3968.0,2006-08-01
97933,ACCENTURE PLC (Accenture Ltd prior to 09/2009),573.0,Karl-Heinz Flöther,142129.0,Division Group Chief Executive,Karl-Heinz Flöther joined this role in Feb 2003,1.93,USD,2326.0,1405.0,3731.0,2007-08-01
97934,ACCENTURE PLC (Accenture Ltd prior to 09/2009),573.0,Karl-Heinz Flöther,142129.0,Division Group Chief Executive,Karl-Heinz Flöther joined this role in Feb 2003,-0.6,USD,1634.0,<NA>,1634.0,2008-08-01
97935,ACCENTURE PLC (Accenture Ltd prior to 09/2009),573.0,Karl-Heinz Flöther,142129.0,Division Group Chief Executive,Karl-Heinz Flöther joined this role in Feb 2003,-0.18,USD,1237.0,<NA>,1237.0,2009-08-01
88578,ACCENTURE PLC (Accenture Ltd prior to 09/2009),573.0,Kevin Campbell,205598.0,Division Group Chief Executive,Kevin Campbell joined this role on 01 Sep 2006,<NA>,USD,1123.0,<NA>,1123.0,2009-08-01
1507,ACCENTURE PLC (Accenture Ltd prior to 09/2009),573.0,Marty Cole,447483.0,Division Group Chief Executive,Marty Cole joined this role on 01 Mar 2012,<NA>,USD,1136.0,<NA>,1136.0,2012-08-01
1508,ACCENTURE PLC (Accenture Ltd prior to 09/2009),573.0,Marty Cole,447483.0,Division Group Chief Executive,Marty Cole joined this role on 01 Mar 2012,-0.07,USD,1136.0,<NA>,1136.0,2013-08-01
223200,ACCENTURE PLC (Accenture Ltd prior to 09/2009),573.0,Sander van't Noordende,513652.0,Division Chief Executive,Sander van't Noordende has changed role on 01 ...,<NA>,USD,1293.0,<NA>,1293.0,2011-08-01
223201,ACCENTURE PLC (Accenture Ltd prior to 09/2009),573.0,Sander van't Noordende,513652.0,Division Chief Executive,Sander van't Noordende joined this role on 01 ...,0.07,USD,1136.0,<NA>,1136.0,2012-08-01
223202,ACCENTURE PLC (Accenture Ltd prior to 09/2009),573.0,Sander van't Noordende,513652.0,Division Group Chief Executive,Sander van't Noordende joined this role on 01 ...,<NA>,USD,1136.0,<NA>,1136.0,2015-08-01
223203,ACCENTURE PLC (Accenture Ltd prior to 09/2009),573.0,Sander van't Noordende,513652.0,Division Group Chief Executive,Sander van't Noordende joined this role on 01 ...,0.3,USD,1136.0,<NA>,1136.0,2016-08-01
223204,ACCENTURE PLC (Accenture Ltd prior to 09/2009),573.0,Sander van't Noordende,513652.0,Division Group Chief Executive,Sander van't Noordende joined this role on 01 ...,-0.03,USD,1136.0,<NA>,1136.0,2017-08-01
223205,ACCENTURE PLC (Accenture Ltd prior to 09/2009),573.0,Sander van't Noordende,513652.0,Division Group Chief Executive,Sander van't Noordende joined this role on 01 ...,0.25,USD,1318.0,<NA>,1318.0,2018-08-01
223206,ACCENTURE PLC (Accenture Ltd prior to 09/2009),573.0,Sander van't Noordende,513652.0,Division Group Chief Executive,Sander van't Noordende joined this role on 01 ...,0.1,USD,1136.0,<NA>,1136.0,2019-08-01
7808,ACCOR SA,598.0,Denis Hennequin,487504.0,CEO,Denis Hennequin has changed role on 01 Dec 2010,<NA>,USD,114.0,<NA>,114.0,2010-12-01
7811,ACCOR SA,598.0,Denis Hennequin,487504.0,Chairman/CEO,Denis Hennequin has changed role on 15 Jan 2011,<NA>,USD,1017.0,14.0,1031.0,2011-12-01
7812,ACCOR SA,598.0,Denis Hennequin,487504.0,Chairman/CEO,Denis Hennequin joined this role on 15 Jan 2011,0.52,USD,1101.0,1998.0,3099.0,2012-12-01
7867,ACCOR SA,598.0,Gilles Pélisson,28079.0,CEO,Gilles Pélisson joined this role on 09 Jan 2006,-0.25,USD,1326.0,1608.0,2933.0,2007-12-01
7868,ACCOR SA,598.0,Gilles Pélisson,28079.0,CEO,Gilles Pélisson joined this role on 09 Jan 2006,0.57,USD,1409.0,1892.0,3301.0,2008-12-01
7869,ACCOR SA,598.0,Gilles Pélisson,28079.0,Chairman/CEO,Gilles Pélisson has changed role on 24 Feb 2009,<NA>,USD,1454.0,1075.0,2528.0,2009-12-01
7932,ACCOR SA,598.0,Jean-Marc Espalioux,15369.0,Chairman/CEO,Jean-Marc Espalioux joined this role on 07 Jan...,<NA>,USD,1481.0,<NA>,1481.0,2001-12-01
7933,ACCOR SA,598.0,Jean-Marc Espalioux,15369.0,Chairman/CEO,Jean-Marc Espalioux joined this role on 07 Jan...,-0.77,USD,1675.0,<NA>,1675.0,2002-12-01
7934,ACCOR SA,598.0,Jean-Marc Espalioux,15369.0,Chairman/CEO,Jean-Marc Espalioux joined this role on 07 Jan...,-0.57,USD,1906.0,<NA>,1906.0,2003-12-01
7935,ACCOR SA,598.0,Jean-Marc Espalioux,15369.0,Chairman/CEO,Jean-Marc Espalioux joined this role on 07 Jan...,0.46,USD,1400.0,816.0,2216.0,2004-12-01
7936,ACCOR SA,598.0,Jean-Marc Espalioux,15369.0,Chairman/CEO,Jean-Marc Espalioux joined this role on 07 Jan...,0.54,USD,1226.0,715.0,1941.0,2005-12-01
8091,ACCOR SA,598.0,Sébastien Bazin,331870.0,Group Chairman/CEO,Sébastien Bazin has changed role on 27 Aug 2013,<NA>,USD,484.0,<NA>,484.0,2013-12-01
8093,ACCOR SA,598.0,Sébastien Bazin,331870.0,Group Chairman/CEO,Sébastien Bazin joined this role on 27 Aug 2013,3.24,USD,1074.0,611.0,1685.0,2014-12-01
8094,ACCOR SA,598.0,Sébastien Bazin,331870.0,Group Chairman/CEO,Sébastien Bazin joined this role on 27 Aug 2013,-0.36,USD,929.0,1496.0,2425.0,2015-12-01
8095,ACCOR SA,598.0,Sébastien Bazin,331870.0,Group Chairman/CEO,Sébastien Bazin joined this role on 27 Aug 2013,1.02,USD,1001.0,1587.0,2588.0,2016-12-01
8096,ACCOR SA,598.0,Sébastien Bazin,331870.0,Group Chairman/CEO,Sébastien Bazin joined this role on 27 Aug 2013,1.62,USD,1140.0,706.0,1846.0,2017-12-01
8097,ACCOR SA,598.0,Sébastien Bazin,331870.0,Group Chairman/CEO,Sébastien Bazin joined this role on 27 Aug 2013,-0.61,USD,1093.0,1732.0,2825.0,2018-12-01
8098,ACCOR SA,598.0,Sébastien Bazin,331870.0,Group Chairman/CEO,Sébastien Bazin joined this role on 27 Aug 2013,0.44,USD,1066.0,1577.0,2642.0,2019-12-01
8099,ACCOR SA,598.0,Sébastien Bazin,331870.0,Group Chairman/CEO,Sébastien Bazin joined this role on 27 Aug 2013,-0.06,USD,943.0,1376.0,2320.0,2020-12-01
8100,ACCOR SA,598.0,Sébastien Bazin,331870.0,Group Chairman/CEO,Sébastien Bazin joined this role on 27 Aug 2013,-0.3,USD,1081.0,711.0,1792.0,2021-12-01
8101,ACCOR SA,598.0,Sébastien Bazin,331870.0,Group Chairman/CEO,Sébastien Bazin joined this role on 27 Aug 2013,0.27,USD,1017.0,1521.0,2538.0,2022-12-01
8102,ACCOR SA,598.0,Sébastien Bazin,331870.0,Group Chairman/CEO,Sébastien Bazin joined this role on 27 Aug 2013,0.25,USD,1048.0,1721.0,2769.0,2023-12-01

In [71]:
df_final.totalcompensation.isna().sum()

np.int64(0)

In [55]:
df_remun_test_ceo.annualreportdate.isna().sum()

np.int64(1082)

In [56]:
df_remun_test_ceo.totalcompensation.isna().sum()

np.int64(14639)

In [44]:
df_remun_test.rolename.value_counts().head(30)

rolename
Independent Board Member                                 46247
Board Member - SD                                        38418
Independent Director                                     32013
Employee Representative                                  16011
Director - SD                                            15612
Chairman                                                 11574
Board Member - ED                                         6469
Chairman/CEO                                              5504
Chairman (Independent Board Member)                       5228
Independent NED                                           5168
CEO                                                       4868
CFO                                                       4429
Shareholder Representative                                3965
Vice Chairman                                             3436
Independent Chairman                                      2715
Independent Shareholder Representative                    2610
Shareholder Representative (Independent Board Member)     2584
President/CEO                                             2516
Deputy Chairman                                           2501
Representative Director                                   2346
Permanent Representative                                  1631
Vice Chairman (Independent Board Member)                  1583
NED                                                       1582
Chairman (Executive)                                      1381
Representative Board Member                               1348
Employee Representative (Independent Board Member)        1345
Chairman (Non-Executive)                                  1304
Independent Vice Chairman                                 1249
Employee Representative (Independent)                     1122
COO                                                       1064
Name: count, dtype: Int64

In [ ]:
df_ceo_only.head(20)

,directorid,directorname,title,companyname,companyid,rolename,datestartrole,dateendrole,is_ceo
2276,342366.0,Simon Borrows,Mr,3I GROUP PLC,294.0,CEO,2012-05-17,9000-01-01,True
15513,534736.0,Søren Skou,Mr,A.P. MOLLER-MAERSK A/S,250471.0,CEO,2016-07-01,2023-01-01,True
15693,1526460.0,Vincent Clerc,Mr,A.P. MOLLER-MAERSK A/S,250471.0,CEO,2023-01-01,9000-01-01,True
1514,1587233.0,Luca Camerano,Mr,A2A SPA,953.0,CEO,2014-06-16,2017-07-11,True
2560,654106.0,Wim Pelsma,Mr,AALBERTS NV (Aalberts Industries NV prior to 0...,384.0,CEO,2012-04-26,2023-09-07,True
2358,1542238.0,Stéphane Simonetta,Mr,AALBERTS NV (Aalberts Industries NV prior to 0...,384.0,CEO,2023-09-07,9000-01-01,True
3128,2124756.0,David Mindus,Mr,AB SAGAX,598834.0,CEO,2007-10-08,9000-01-01,True
231,32417.0,Björn Rosengren,Mr,ABB LTD,422.0,CEO,2020-03-01,2024-07-31,True
1839,2160278.0,Morten Wierod,Mr,ABB LTD,422.0,CEO,2024-08-01,9000-01-01,True
2089,1663966.0,Professor Doctor Hartmut Ehrlich,Professor Doctor,ABIVAX SA,2168332.0,CEO,2015-06-26,2023-05-05,True
1545,33413.0,Marc De Garidel,Mr,ABIVAX SA,2168332.0,CEO,2024-07-15,9000-01-01,True
1594,1204635.0,Marguerite Bérard-Andrieu,Ms,ABN AMRO BANK NV (ABN Amro Group NV prior to 0...,2364797.0,CEO,2025-04-23,9000-01-01,True
3092,1759555.0,Daniel Bischofberger,Mr,ACCELLERON INDUSTRIES AG,3570291.0,CEO,2022-10-03,9000-01-01,True
2691,1850311.0,André Clark Juliano,Mr,ACCIONA SA,595.0,CEO,2016-04-01,2017-09-28,True
3581,28079.0,Gilles Pélisson,Mr,ACCOR SA,598.0,CEO,2006-01-09,2009-02-24,True
3140,487504.0,Denis Hennequin,Mr,ACCOR SA,598.0,CEO,2010-12-01,2011-01-15,True
5031,30344.0,Yann Caillère,Mr,ACCOR SA,598.0,CEO,2013-04-23,2013-08-27,True
3892,650646.0,Jorge Guarner Muñoz,Mr,ACERINOX SA,626.0,CEO,1982-01-01,1992-12-28,True
2891,348417.0,Bernardo Velázquez Herreros,Mr,ACERINOX SA,626.0,CEO,2010-07-27,9000-01-01,True
3734,328420.0,Jan Suykens,Mr,ACKERMANS & VAN HAAREN NV,640.0,CEO,2016-05-23,2022-05-23,True

In [ ]:
#test = df_ceo_only.merge(df_remun, on= 'directorid', how = 'inner')
# test.head(15)

In [ ]:
CEO_PATTERN = r"chief executive|(?<!\w)ceo(?!\w)|managing director"
df_remun["is_ceo"] = df_remun["rolename"].str.lower().str.contains(CEO_PATTERN, na=False, regex=True)
df_remun_new = df_remun[df_remun["is_ceo"]].copy()

In [ ]:
df_remun_new

,boardname,boardid,directorname,directorid,rolename,rolestatus,remchgelast,currency,salary,bonus,totalcompensation,annualreportdate,is_ceo
22,ADIDAS AG (Adidas-Salomon prior to 06/2006),792.0,Björn Gulden,1139597.0,CEO,Björn Gulden joined this role on 01 Jan 2023,<NA>,USD,2428.0,2023.0,4451.0,2023-12-01,True
23,ADIDAS AG (Adidas-Salomon prior to 06/2006),792.0,Björn Gulden,1139597.0,CEO,Björn Gulden joined this role on 01 Jan 2023,-0.26,USD,2278.0,2278.0,4556.0,2024-12-01,True
24,ADIDAS AG (Adidas-Salomon prior to 06/2006),792.0,Björn Gulden,1139597.0,CEO,Björn Gulden joined this role on 01 Jan 2023,0.05,USD,2584.0,2584.0,5168.0,2025-12-01,True
35,AIB GROUP PLC (Allied Irish Banks PLC prior to...,1505.0,Bernard Byrne,1072794.0,CEO,Bernard Byrne has changed role on 29 May 2015,<NA>,USD,524.0,<NA>,524.0,2015-12-01,True
36,AIB GROUP PLC (Allied Irish Banks PLC prior to...,1505.0,Bernard Byrne,1072794.0,CEO,Bernard Byrne joined this role on 29 May 2015,0.21,USD,527.0,<NA>,527.0,2016-12-01,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10910,VOLKSWAGEN AG,32910.0,Thomas Schäfer,2364469.0,Division Chairman/Division CEO,Thomas Schäfer joined this role on 01 Jul 2022,-0.37,USD,1655.0,2199.0,3855.0,2023-12-01,True
10911,VOLKSWAGEN AG,32910.0,Thomas Schäfer,2364469.0,Division Chairman/Division CEO,Thomas Schäfer joined this role on 01 Jul 2022,-0.13,USD,1475.0,1777.0,3252.0,2024-12-01,True
10916,ZALANDO SE,2154485.0,Rubin Ritter,1461711.0,Co-CEO,Rubin Ritter joined this role in 2017,<NA>,USD,73.0,<NA>,73.0,2019-12-01,True
10917,ZALANDO SE,2154485.0,Rubin Ritter,1461711.0,Co-CEO,Rubin Ritter joined this role in 2017,0.06,USD,79.0,<NA>,79.0,2020-12-01,True
10927,ZURICH INSURANCE GROUP AG,34200.0,Tom de Swaan,15011.0,Chairman/Interim CEO,Tom de Swaan has changed role on 01 Dec 2015,<NA>,USD,738.0,<NA>,738.0,2015-12-01,True

In [ ]:
df_remun_new.head(50)

,boardname,boardid,directorname,directorid,rolename,rolestatus,remchgelast,currency,salary,bonus,totalcompensation,annualreportdate,is_ceo
22,ADIDAS AG (Adidas-Salomon prior to 06/2006),792.0,Björn Gulden,1139597.0,CEO,Björn Gulden joined this role on 01 Jan 2023,<NA>,USD,2428.0,2023.0,4451.0,2023-12-01,True
23,ADIDAS AG (Adidas-Salomon prior to 06/2006),792.0,Björn Gulden,1139597.0,CEO,Björn Gulden joined this role on 01 Jan 2023,-0.26,USD,2278.0,2278.0,4556.0,2024-12-01,True
24,ADIDAS AG (Adidas-Salomon prior to 06/2006),792.0,Björn Gulden,1139597.0,CEO,Björn Gulden joined this role on 01 Jan 2023,0.05,USD,2584.0,2584.0,5168.0,2025-12-01,True
35,AIB GROUP PLC (Allied Irish Banks PLC prior to...,1505.0,Bernard Byrne,1072794.0,CEO,Bernard Byrne has changed role on 29 May 2015,<NA>,USD,524.0,<NA>,524.0,2015-12-01,True
36,AIB GROUP PLC (Allied Irish Banks PLC prior to...,1505.0,Bernard Byrne,1072794.0,CEO,Bernard Byrne joined this role on 29 May 2015,0.21,USD,527.0,<NA>,527.0,2016-12-01,True
37,AIB GROUP PLC (Allied Irish Banks PLC prior to...,1505.0,Bernard Byrne,1072794.0,CEO,Bernard Byrne joined this role on 29 May 2015,0.04,USD,600.0,<NA>,600.0,2017-12-01,True
38,AIB GROUP PLC (Allied Irish Banks PLC prior to...,1505.0,Bernard Byrne,1072794.0,CEO,Bernard Byrne joined this role on 29 May 2015,0.02,USD,575.0,<NA>,575.0,2018-12-01,True
52,AIR LIQUIDE SA,1168.0,Alain Joly,15840.0,Chairman/CEO,Alain Joly joined this role in May 1995,<NA>,USD,762.0,<NA>,762.0,2000-12-01,True
71,AIR LIQUIDE SA,1168.0,Benoît Potier,5736.0,Chairman/CEO,Benoît Potier has changed role on 10 May 2006,<NA>,USD,1244.0,1668.0,2912.0,2006-12-01,True
72,AIR LIQUIDE SA,1168.0,Benoît Potier,5736.0,Chairman/CEO,Benoît Potier has changed role on 10 May 2006,<NA>,USD,1244.0,1668.0,2912.0,2006-12-01,True
73,AIR LIQUIDE SA,1168.0,Benoît Potier,5736.0,Chairman/CEO,Benoît Potier joined this role on 10 May 2006,0.47,USD,1475.0,1809.0,3284.0,2007-12-01,True
74,AIR LIQUIDE SA,1168.0,Benoît Potier,5736.0,Chairman/CEO,Benoît Potier joined this role on 10 May 2006,0.0,USD,1421.0,2002.0,3423.0,2008-12-01,True
75,AIR LIQUIDE SA,1168.0,Benoît Potier,5736.0,Chairman/CEO,Benoît Potier joined this role on 10 May 2006,0.69,USD,1467.0,2138.0,3605.0,2009-12-01,True
76,AIR LIQUIDE SA,1168.0,Benoît Potier,5736.0,Chairman/CEO,Benoît Potier joined this role on 10 May 2006,0.69,USD,1467.0,2138.0,3605.0,2009-12-01,True
77,AIR LIQUIDE SA,1168.0,Benoît Potier,5736.0,Chairman/CEO,Benoît Potier joined this role on 10 May 2006,0.04,USD,1469.0,1568.0,3037.0,2010-12-01,True
78,AIR LIQUIDE SA,1168.0,Benoît Potier,5736.0,Chairman/CEO,Benoît Potier joined this role on 10 May 2006,0.04,USD,1469.0,1568.0,3037.0,2010-12-01,True
79,AIR LIQUIDE SA,1168.0,Benoît Potier,5736.0,Chairman/CEO,Benoît Potier joined this role on 10 May 2006,0.01,USD,1372.0,2058.0,3429.0,2011-12-01,True
80,AIR LIQUIDE SA,1168.0,Benoît Potier,5736.0,Chairman/CEO,Benoît Potier joined this role on 10 May 2006,0.01,USD,1372.0,2058.0,3429.0,2011-12-01,True
81,AIR LIQUIDE SA,1168.0,Benoît Potier,5736.0,Chairman/CEO,Benoît Potier joined this role on 10 May 2006,-0.02,USD,1427.0,2153.0,3580.0,2012-12-01,True
82,AIR LIQUIDE SA,1168.0,Benoît Potier,5736.0,Chairman/CEO,Benoît Potier joined this role on 10 May 2006,-0.02,USD,1427.0,2153.0,3580.0,2012-12-01,True
83,AIR LIQUIDE SA,1168.0,Benoît Potier,5736.0,Chairman/CEO,Benoît Potier joined this role on 10 May 2006,-0.4,USD,1518.0,2282.0,3800.0,2013-12-01,True
84,AIR LIQUIDE SA,1168.0,Benoît Potier,5736.0,Chairman/CEO,Benoît Potier joined this role on 10 May 2006,-0.63,USD,1338.0,1817.0,3154.0,2014-12-01,True
85,AIR LIQUIDE SA,1168.0,Benoît Potier,5736.0,Chairman/CEO,Benoît Potier joined this role on 10 May 2006,1.68,USD,1202.0,1895.0,3098.0,2015-12-01,True
86,AIR LIQUIDE SA,1168.0,Benoît Potier,5736.0,Chairman/CEO,Benoît Potier joined this role on 10 May 2006,0.07,USD,1238.0,1734.0,2971.0,2016-12-01,True
87,AIR LIQUIDE SA,1168.0,Benoît Potier,5736.0,Chairman/CEO,Benoît Potier joined this role on 10 May 2006,-0.17,USD,1530.0,1510.0,3040.0,2017-12-01,True
88,AIR LIQUIDE SA,1168.0,Benoît Potier,5736.0,Chairman/CEO,Benoît Potier joined this role on 10 May 2006,-0.39,USD,1525.0,2245.0,3769.0,2018-12-01,True
89,AIR LIQUIDE SA,1168.0,Benoît Potier,5736.0,Chairman/CEO,Benoît Potier joined this role on 10 May 2006,0.63,USD,1486.0,2250.0,3736.0,2019-12-01,True
90,AIR LIQUIDE SA,1168.0,Benoît Potier,5736.0,Chairman/CEO,Benoît Potier joined this role on 10 May 2006,0.07,USD,1620.0,2524.0,4144.0,2020-12-01,True
91,AIR LIQUIDE SA,1168.0,Benoît Potier,5736.0,Chairman/CEO,Benoît Potier joined this role on 10 May 2006,-0.08,USD,1507.0,1661.0,3168.0,2021-12-01,True
101,ALCATEL-LUCENT SA (Alcatel prior to 12/2006) (...,1307.0,Ben Verwaayen,17103.0,CEO,Ben Verwaayen has changed role on 15 Sep 2008,<NA>,USD,1682.0,49.0,1731.0,2008-12-01,True
102,ALCATEL-LUCENT SA (Alcatel prior to 12/2006) (...,1307.0,Ben Verwaayen,17103.0,CEO,Ben Verwaayen joined this role on 15 Sep 2008,0.31,USD,1719.0,<NA>,1719.0,2009-12-01,True
103,ALCATEL-LUCENT SA (Alcatel prior to 12/2006) (...,1307.0,Ben Verwaayen,17103.0,CEO,Ben Verwaayen joined this role on 15 Sep 2008,-0.24,USD,1607.0,<NA>,1607.0,2010-12-01,True
104,ALCATEL-LUCENT SA (Alcatel prior to 12/2006) (...,1307.0,Ben Verwaayen,17103.0,CEO,Ben Verwaayen joined this role on 15 Sep 2008,-0.09,USD,1553.0,<NA>,1553.0,2011-12-01,True
105,ALCATEL-LUCENT SA (Alcatel prior to 12/2006) (...,1307.0,Ben Verwaayen,17103.0,CEO,Ben Verwaayen joined this role on 15 Sep 2008,-0.17,USD,1585.0,<NA>,1585.0,2012-12-01,True
120,ANHEUSER-BUSCH INBEV SA (InBev SA prior to 11/...,16308.0,Carlos Alves de Brito,220496.0,CEO,Carlos Alves de Brito has changed role on 01 M...,<NA>,USD,931.0,<NA>,931.0,2006-12-01,True
125,ARCELORMITTAL SA (Arcelor SA prior to 11/2007),50431.0,Aditya Mittal,481549.0,CEO,Aditya Mittal has changed role on 11 Feb 2021,<NA>,USD,1783.0,2226.0,4009.0,2021-12-01,True
126,ARCELORMITTAL SA (Arcelor SA prior to 11/2007),50431.0,Aditya Mittal,481549.0,CEO,Aditya Mittal joined this role on 11 Feb 2021,0.33,USD,1670.0,3335.0,5005.0,2022-12-01,True
127,ARCELORMITTAL SA (Arcelor SA prior to 11/2007),50431.0,Aditya Mittal,481549.0,CEO,Aditya Mittal joined this role on 11 Feb 2021,-0.48,USD,1678.0,<NA>,1678.0,2023-12-01,True
128,ARCELORMITTAL SA (Arcelor SA prior to 11/2007),50431.0,Aditya Mittal,481549.0,CEO,Aditya Mittal joined this role on 11 Feb 2021,0.29,USD,1791.0,<NA>,1791.0,2024-12-01,True
148,ASML HOLDING NV (ASM Lithography Holding NV pr...,2781.0,Christophe Fouquet,1987178.0,President/CEO,Christophe Fouquet has changed role on 24 Apr ...,<NA>,USD,1014.0,1586.0,2600.0,2024-12-01,True
180,AXA SA,3270.0,Alfred Bouckaert,28291.0,Regional CEO,Alfred Bouckaert has changed role on 11 Oct 2006,<NA>,USD,966.0,878.0,1844.0,2006-12-01,True
181,AXA SA,3270.0,Alfred Bouckaert,28291.0,Regional CEO,Alfred Bouckaert has changed role on 11 Oct 2006,<NA>,USD,966.0,878.0,1844.0,2006-12-01,True
182,AXA SA,3270.0,Alfred Bouckaert,28291.0,Regional CEO,Alfred Bouckaert joined this role on 11 Oct 2006,0.27,USD,1138.0,1136.0,2274.0,2007-12-01,True
183,AXA SA,3270.0,Alfred Bouckaert,28291.0,Regional CEO,Alfred Bouckaert joined this role on 11 Oct 2006,0.27,USD,1138.0,1136.0,2274.0,2007-12-01,True
184,AXA SA,3270.0,Alfred Bouckaert,28291.0,Regional CEO,Alfred Bouckaert joined this role on 11 Oct 2006,0.84,USD,1551.0,1051.0,2603.0,2008-12-01,True
185,AXA SA,3270.0,Alfred Bouckaert,28291.0,Regional CEO,Alfred Bouckaert joined this role on 11 Oct 2006,0.84,USD,1551.0,1051.0,2603.0,2008-12-01,True
186,AXA SA,3270.0,Alfred Bouckaert,28291.0,Regional CEO,Alfred Bouckaert joined this role on 11 Oct 2006,-0.17,USD,1647.0,1075.0,2721.0,2009-12-01,True
191,BANCO SANTANDER SA (Banco Santander Central Hi...,3837.0,Alfredo Sáenz Abad,5883.0,Second Vice Chairman/CEO,Alfredo Sáenz Abad has changed role on 13 Feb ...,<NA>,USD,2497.0,2393.0,4890.0,2002-12-01,True
192,BANCO SANTANDER SA (Banco Santander Central Hi...,3837.0,Alfredo Sáenz Abad,5883.0,Second Vice Chairman/CEO,Alfredo Sáenz Abad joined this role on 13 Feb ...,0.22,USD,3247.0,3358.0,6605.0,2003-12-01,True
193,BANCO SANTANDER SA (Banco Santander Central Hi...,3837.0,Alfredo Sáenz Abad,5883.0,Second Vice Chairman/CEO,Alfredo Sáenz Abad joined this role on 13 Feb ...,0.47,USD,3630.0,4218.0,7849.0,2004-12-01,True

In [ ]:
len(df_remun_new.boardname.unique())

176

In [ ]:
df_ceo_emp[df_ceo_emp['directorid'] == 534736.0]

,directorid,directorname,title,companyname,companyid,rolename,datestartrole,dateendrole,is_ceo
15515,534736.0,Søren Skou,Mr,A.P. MOLLER-MAERSK A/S,250471.0,Executive VP/Division CEO,2003-11-01,2007-07-01,True
15516,534736.0,Søren Skou,Mr,A.P. MOLLER-MAERSK A/S,250471.0,Partner/Division CEO,2007-07-01,2011-12-28,True
15514,534736.0,Søren Skou,Mr,A.P. MOLLER-MAERSK A/S,250471.0,Division CEO,2012-01-16,2016-07-01,True
15513,534736.0,Søren Skou,Mr,A.P. MOLLER-MAERSK A/S,250471.0,CEO,2016-07-01,2023-01-01,True

In [ ]:
df_remun[df_remun['directorid'] == 534736.0]

,boardname,boardid,directorname,directorid,rolename,rolestatus,remchgelast,currency,salary,bonus,totalcompensation,annualreportdate
10459,NOKIA OYJ,22335.0,Søren Skou,534736.0,Independent Board Member,Søren Skou joined this role on 21 May 2019,<NA>,USD,179.0,<NA>,179.0,2019-12-01
10460,NOKIA OYJ,22335.0,Søren Skou,534736.0,Independent Board Member,Søren Skou joined this role on 21 May 2019,0.06,USD,196.0,<NA>,196.0,2020-12-01
10461,NOKIA OYJ,22335.0,Søren Skou,534736.0,Independent Board Member,Søren Skou joined this role on 21 May 2019,0.03,USD,199.0,<NA>,199.0,2021-12-01
10462,NOKIA OYJ,22335.0,Søren Skou,534736.0,Vice Chair (Independent Board Member),Søren Skou has changed role on 05 Apr 2022,<NA>,USD,225.0,<NA>,225.0,2022-12-01
10463,NOKIA OYJ,22335.0,Søren Skou,534736.0,Vice Chair (Independent Board Member),Søren Skou joined this role on 05 Apr 2022,0.05,USD,248.0,<NA>,248.0,2023-12-01
10464,NOKIA OYJ,22335.0,Søren Skou,534736.0,Vice Chair (Independent Board Member),Søren Skou joined this role on 05 Apr 2022,-0.07,USD,228.0,<NA>,228.0,2024-12-01

---

In [ ]:
display(df_ceo_emp[df_ceo_emp['directorid'] == 882159.0])
display(df_remun[df_remun['directorid'] == 882159.0])

,directorid,directorname,title,companyname,companyid,rolename,datestartrole,dateendrole,is_ceo
95550,882159.0,Mike Kerner,Mr,ZURICH INSURANCE GROUP AG,34200.0,Division Regional CEO,2009-06-01,2012-09-01,True
95549,882159.0,Mike Kerner,Mr,ZURICH INSURANCE GROUP AG,34200.0,Division CEO,2012-09-01,2015-10-01,True

,boardname,boardid,directorname,directorid,rolename,rolestatus,remchgelast,currency,salary,bonus,totalcompensation,annualreportdate
8759,MUNCHENER RUCKVERSICHERUNGS AG (Munich Re),21321.0,Mike Kerner,882159.0,Board Member - ED,Mike Kerner joined this role on 01 Jan 2023,<NA>,USD,1583.0,<NA>,1583.0,2023-12-01
8760,MUNCHENER RUCKVERSICHERUNGS AG (Munich Re),21321.0,Mike Kerner,882159.0,Board Member - ED,Mike Kerner joined this role on 01 Jan 2023,0.65,USD,1746.0,816.0,2561.0,2024-12-01

___

In [ ]:
import pandas as pd

# Make copies
remun = df_remun.copy()
ceo_emp = df_ceo_emp.copy()

# Convert date columns
remun["annualreportdate"] = pd.to_datetime(remun["annualreportdate"], errors="coerce")
ceo_emp["datestartrole"] = pd.to_datetime(ceo_emp["datestartrole"], errors="coerce")
ceo_emp["dateendrole"] = pd.to_datetime(ceo_emp["dateendrole"], errors="coerce")

# Optional: if dateendrole is missing, treat as still active
ceo_emp["dateendrole"] = ceo_emp["dateendrole"].fillna(pd.Timestamp.today())

# Keep only CEO rows from employment table
ceo_emp_only = ceo_emp[ceo_emp["is_ceo"] == True].copy()

# Merge remuneration with CEO role periods
df_remun_ceo = remun.merge(
    ceo_emp_only[[
        "directorid",
        "directorname",
        "companyid",
        "companyname",
        "rolename",
        "datestartrole",
        "dateendrole"
    ]],
    on="directorid",
    how="inner",
    suffixes=("_remun", "_ceo")
)

# Filter where annual report date is within CEO role period
df_remun_ceo = df_remun_ceo[['companyid', 'companyname', 'directorname_ceo', 'directorid', 'rolename_ceo', 'rolename_remun', 'currency', 'salary', 'bonus', 'totalcompensation', 'remchgelast', 'annualreportdate', 'datestartrole', 'dateendrole']]
df_remun_ceo = df_remun_ceo[df_remun_ceo['totalcompensation'] > 0]

df_remun_ceo_filtered = df_remun_ceo[
    (df_remun_ceo["annualreportdate"] >= df_remun_ceo["datestartrole"]) &
    (df_remun_ceo["annualreportdate"] <= df_remun_ceo["dateendrole"])
].copy()

In [ ]:
df_remun_ceo.sort_values(by=['companyname', 'datestartrole', 'annualreportdate']).tail(50)

,companyid,companyname,directorname_ceo,directorid,rolename_ceo,rolename_remun,currency,salary,bonus,totalcompensation,remchgelast,annualreportdate,datestartrole,dateendrole
2873,34200.0,ZURICH INSURANCE GROUP AG,Doctor Thomas Buberl,654634.0,Regional CEO,CEO,USD,1697.0,1720.0,3418.0,0.08,2022-12-01,2009-01-01,2012-04-28 00:00:00.000000
2878,34200.0,ZURICH INSURANCE GROUP AG,Doctor Thomas Buberl,654634.0,Regional CEO,CEO,USD,1821.0,1932.0,3753.0,0.23,2023-12-01,2009-01-01,2012-04-28 00:00:00.000000
2883,34200.0,ZURICH INSURANCE GROUP AG,Doctor Thomas Buberl,654634.0,Regional CEO,CEO,USD,1708.0,1956.0,3664.0,-0.02,2024-12-01,2009-01-01,2012-04-28 00:00:00.000000
2888,34200.0,ZURICH INSURANCE GROUP AG,Doctor Thomas Buberl,654634.0,Regional CEO,CEO,USD,1915.0,<NA>,1915.0,<NA>,NaT,2009-01-01,2012-04-28 00:00:00.000000
15109,34200.0,ZURICH INSURANCE GROUP AG,Mike Kerner,882159.0,Division Regional CEO,Board Member - ED,USD,1583.0,<NA>,1583.0,<NA>,2023-12-01,2009-06-01,2012-09-01 00:00:00.000000
15111,34200.0,ZURICH INSURANCE GROUP AG,Mike Kerner,882159.0,Division Regional CEO,Board Member - ED,USD,1746.0,816.0,2561.0,0.65,2024-12-01,2009-06-01,2012-09-01 00:00:00.000000
1642,34200.0,ZURICH INSURANCE GROUP AG,Claudia Dill,1017142.0,Division CEO,Independent Board Member,USD,138.0,<NA>,138.0,<NA>,2021-12-01,2009-09-01,2012-07-01 00:00:00.000000
15110,34200.0,ZURICH INSURANCE GROUP AG,Mike Kerner,882159.0,Division CEO,Board Member - ED,USD,1583.0,<NA>,1583.0,<NA>,2023-12-01,2012-09-01,2015-10-01 00:00:00.000000
15112,34200.0,ZURICH INSURANCE GROUP AG,Mike Kerner,882159.0,Division CEO,Board Member - ED,USD,1746.0,816.0,2561.0,0.65,2024-12-01,2012-09-01,2015-10-01 00:00:00.000000
1643,34200.0,ZURICH INSURANCE GROUP AG,Claudia Dill,1017142.0,Regional CEO,Independent Board Member,USD,138.0,<NA>,138.0,<NA>,2021-12-01,2015-05-01,2020-09-02 00:00:00.000000
16613,34200.0,ZURICH INSURANCE GROUP AG,Tom de Swaan,15011.0,Chairman/Interim CEO,CFO,USD,526.0,745.0,1271.0,3.78,2000-12-01,2015-12-01,2016-03-07 00:00:00.000000
16614,34200.0,ZURICH INSURANCE GROUP AG,Tom de Swaan,15011.0,Chairman/Interim CEO,CFO,USD,560.0,224.0,784.0,0.29,2001-12-01,2015-12-01,2016-03-07 00:00:00.000000
16615,34200.0,ZURICH INSURANCE GROUP AG,Tom de Swaan,15011.0,Chairman/Interim CEO,CFO,USD,662.0,506.0,1168.0,0.08,2002-12-01,2015-12-01,2016-03-07 00:00:00.000000
16616,34200.0,ZURICH INSURANCE GROUP AG,Tom de Swaan,15011.0,Chairman/Interim CEO,CFO,USD,791.0,716.0,1506.0,0.18,2003-12-01,2015-12-01,2016-03-07 00:00:00.000000
16617,34200.0,ZURICH INSURANCE GROUP AG,Tom de Swaan,15011.0,Chairman/Interim CEO,CFO,USD,864.0,782.0,1646.0,-0.17,2004-12-01,2015-12-01,2016-03-07 00:00:00.000000
16618,34200.0,ZURICH INSURANCE GROUP AG,Tom de Swaan,15011.0,Chairman/Interim CEO,CFO,USD,774.0,891.0,1665.0,0.13,2005-12-01,2015-12-01,2016-03-07 00:00:00.000000
17103,34200.0,ZURICH INSURANCE GROUP AG,Tom de Swaan,15011.0,Chairman/Interim CEO,Independent Board Member,USD,11.0,<NA>,11.0,<NA>,2006-12-01,2015-12-01,2016-03-07 00:00:00.000000
18661,34200.0,ZURICH INSURANCE GROUP AG,Tom de Swaan,15011.0,Chairman/Interim CEO,Independent Director,USD,115.0,<NA>,115.0,<NA>,2006-12-01,2015-12-01,2016-03-07 00:00:00.000000
17104,34200.0,ZURICH INSURANCE GROUP AG,Tom de Swaan,15011.0,Chairman/Interim CEO,Independent Board Member,USD,75.0,<NA>,75.0,5.57,2007-12-01,2015-12-01,2016-03-07 00:00:00.000000
17506,34200.0,ZURICH INSURANCE GROUP AG,Tom de Swaan,15011.0,Chairman/Interim CEO,Vice Chairman (Independent Board Member),USD,110.0,<NA>,110.0,<NA>,2007-12-01,2015-12-01,2016-03-07 00:00:00.000000
18662,34200.0,ZURICH INSURANCE GROUP AG,Tom de Swaan,15011.0,Chairman/Interim CEO,Independent Director,USD,177.0,<NA>,177.0,0.52,2007-12-01,2015-12-01,2016-03-07 00:00:00.000000
17507,34200.0,ZURICH INSURANCE GROUP AG,Tom de Swaan,15011.0,Chairman/Interim CEO,Vice Chairman (Independent Board Member),USD,117.0,<NA>,117.0,0.44,2008-12-01,2015-12-01,2016-03-07 00:00:00.000000
18663,34200.0,ZURICH INSURANCE GROUP AG,Tom de Swaan,15011.0,Chairman/Interim CEO,Independent Director,USD,222.0,<NA>,222.0,0.7,2008-12-01,2015-12-01,2016-03-07 00:00:00.000000
18664,34200.0,ZURICH INSURANCE GROUP AG,Tom de Swaan,15011.0,Chairman/Interim CEO,Independent Director,USD,137.0,<NA>,137.0,-0.44,2009-12-01,2015-12-01,2016-03-07 00:00:00.000000
17508,34200.0,ZURICH INSURANCE GROUP AG,Tom de Swaan,15011.0,Chairman/Interim CEO,Vice Chairman (Independent Board Member),USD,113.0,<NA>,113.0,-0.12,2010-01-01,2015-12-01,2016-03-07 00:00:00.000000
18665,34200.0,ZURICH INSURANCE GROUP AG,Tom de Swaan,15011.0,Chairman/Interim CEO,Independent Director,USD,137.0,<NA>,137.0,0.04,2010-12-01,2015-12-01,2016-03-07 00:00:00.000000
18666,34200.0,ZURICH INSURANCE GROUP AG,Tom de Swaan,15011.0,Chairman/Interim CEO,Independent Director,USD,170.0,<NA>,170.0,0.26,2011-12-01,2015-12-01,2016-03-07 00:00:00.000000
18667,34200.0,ZURICH INSURANCE GROUP AG,Tom de Swaan,15011.0,Chairman/Interim CEO,Independent Vice Chairman,USD,125.0,<NA>,125.0,<NA>,2012-12-01,2015-12-01,2016-03-07 00:00:00.000000
18668,34200.0,ZURICH INSURANCE GROUP AG,Tom de Swaan,15011.0,Chairman/Interim CEO,Independent Chairman,USD,613.0,<NA>,613.0,<NA>,2013-12-01,2015-12-01,2016-03-07 00:00:00.000000
18669,34200.0,ZURICH INSURANCE GROUP AG,Tom de Swaan,15011.0,Chairman/Interim CEO,Independent Chairman,USD,1011.0,<NA>,1011.0,0.75,2014-12-01,2015-12-01,2016-03-07 00:00:00.000000
18670,34200.0,ZURICH INSURANCE GROUP AG,Tom de Swaan,15011.0,Chairman/Interim CEO,Chairman/Interim CEO,USD,738.0,<NA>,738.0,<NA>,2015-12-01,2015-12-01,2016-03-07 00:00:00.000000
18671,34200.0,ZURICH INSURANCE GROUP AG,Tom de Swaan,15011.0,Chairman/Interim CEO,Independent Chairman,USD,736.0,<NA>,736.0,<NA>,2016-12-01,2015-12-01,2016-03-07 00:00:00.000000
18672,34200.0,ZURICH INSURANCE GROUP AG,Tom de Swaan,15011.0,Chairman/Interim CEO,Independent Chairman,USD,797.0,<NA>,797.0,-0.01,2017-12-01,2015-12-01,2016-03-07 00:00:00.000000
12112,34200.0,ZURICH INSURANCE GROUP AG,Mario Greco,22902.0,Group CEO,CEO/MD,USD,347.0,54.0,401.0,<NA>,1998-12-01,2016-03-07,2026-06-11 22:44:27.574835
12116,34200.0,ZURICH INSURANCE GROUP AG,Mario Greco,22902.0,Group CEO,CEO/MD,USD,350.0,16.0,366.0,-0.05,1999-12-01,2016-03-07,2026-06-11 22:44:27.574835
12120,34200.0,ZURICH INSURANCE GROUP AG,Mario Greco,22902.0,Group CEO,CEO/MD,USD,422.0,27.0,449.0,0.69,2000-12-01,2016-03-07,2026-06-11 22:44:27.574835
12124,34200.0,ZURICH INSURANCE GROUP AG,Mario Greco,22902.0,Group CEO,CEO/MD,USD,683.0,<NA>,683.0,0.8,2001-12-01,2016-03-07,2026-06-11 22:44:27.574835
11563,34200.0,ZURICH INSURANCE GROUP AG,Mario Greco,22902.0,Group CEO,Independent Director,USD,2.0,<NA>,2.0,<NA>,2002-12-01,2016-03-07,2026-06-11 22:44:27.574835
12128,34200.0,ZURICH INSURANCE GROUP AG,Mario Greco,22902.0,Group CEO,CEO/MD,USD,920.0,<NA>,920.0,0.11,2002-12-01,2016-03-07,2026-06-11 22:44:27.574835
12900,34200.0,ZURICH INSURANCE GROUP AG,Mario Greco,22902.0,Group CEO,Independent Director,USD,98.0,<NA>,98.0,<NA>,2002-12-01,2016-03-07,2026-06-11 22:44:27.574835
12132,34200.0,ZURICH INSURANCE GROUP AG,Mario Greco,22902.0,Group CEO,CEO/MD,USD,1622.0,<NA>,1622.0,0.42,2003-12-01,2016-03-07,2026-06-11 22:44:27.574835
12904,34200.0,ZURICH INSURANCE GROUP AG,Mario Greco,22902.0,Group CEO,Independent Director,USD,132.0,<NA>,132.0,0.22,2003-12-01,2016-03-07,2026-06-11 22:44:27.574835
12136,34200.0,ZURICH INSURANCE GROUP AG,Mario Greco,22902.0,Group CEO,CEO/MD,USD,908.0,3021.0,3929.0,1.05,2004-12-01,2016-03-07,2026-06-11 22:44:27.574835
12908,34200.0,ZURICH INSURANCE GROUP AG,Mario Greco,22902.0,Group CEO,Independent Director,USD,141.0,<NA>,141.0,-0.01,2004-12-01,2016-03-07,2026-06-11 22:44:27.574835
10638,34200.0,ZURICH INSURANCE GROUP AG,Mario Greco,22902.0,Group CEO,Board Member - SD,USD,55.0,<NA>,55.0,<NA>,2005-12-01,2016-03-07,2026-06-11 22:44:27.574835
11369,34200.0,ZURICH INSURANCE GROUP AG,Mario Greco,22902.0,Group CEO,Group CEO/General Manager,USD,716.0,1717.0,2433.0,<NA>,2012-12-01,2016-03-07,2026-06-11 22:44:27.574835
11373,34200.0,ZURICH INSURANCE GROUP AG,Mario Greco,22902.0,Group CEO,Group CEO/General Manager,USD,716.0,1717.0,2433.0,<NA>,2012-12-01,2016-03-07,2026-06-11 22:44:27.574835
11377,34200.0,ZURICH INSURANCE GROUP AG,Mario Greco,22902.0,Group CEO,CEO/MD/General Manager,USD,1794.0,<NA>,1794.0,<NA>,2013-12-01,2016-03-07,2026-06-11 22:44:27.574835
11381,34200.0,ZURICH INSURANCE GROUP AG,Mario Greco,22902.0,Group CEO,CEO/MD/General Manager,USD,1581.0,2262.0,3843.0,3.26,2014-12-01,2016-03-07,2026-06-11 22:44:27.574835
11385,34200.0,ZURICH INSURANCE GROUP AG,Mario Greco,22902.0,Group CEO,CEO/MD/General Manager,USD,1421.0,2033.0,3454.0,-0.5,2015-12-01,2016-03-07,2026-06-11 22:44:27.574835

---

In [ ]:
conn.list_libraries()

['aha_sample',
 'ahasamp',
 'auditsmp',
 'auditsmp_all',
 'bank',
 'bank_all',
 'bank_premium_samp',
 'banksamp',
 'block',
 'block_all',
 'boardex',
 'boardex_eur',
 'boardex_na',
 'boardex_trial',
 'boardex_uk',
 'boardsmp',
 'bvd_amadeus_trial',
 'bvd_bvdbankf_trial',
 'bvd_orbis_trial',
 'bvdsamp',
 'calcbench_trial',
 'calcbnch',
 'candid_samp',
 'cboe',
 'cboe_all',
 'cboe_sample',
 'cboesamp',
 'cddsamp',
 'ciq',
 'ciq_common',
 'ciq_keydev',
 'ciq_transactions',
 'ciqsamp',
 'ciqsamp_capstrct',
 'ciqsamp_common',
 'ciqsamp_keydev',
 'ciqsamp_pplintel',
 'ciqsamp_ratings',
 'ciqsamp_transactions',
 'ciqsamp_transcripts',
 'cisdmsmp',
 'columnar',
 'comp',
 'comp_bank_daily',
 'comp_execucomp',
 'comp_global_daily',
 'comp_na_daily_all',
 'comp_segments_hist_daily',
 'comp_snapshot',
 'compsamp',
 'compsamp_all',
 'compsamp_computext',
 'compsamp_snapshot',
 'compseg',
 'compsnap',
 'contrib',
 'contrib_as_filed_financials',
 'contrib_ceo_turnover',
 'contrib_corporate_culture',
 'contrib_general',
 'contrib_liva',
 'crspsamp',
 'crspsamp_all',
 'crspsamp_mf',
 'csmsamp_all',
 'djones',
 'djones_all',
 'dmef',
 'dmef_all',
 'doe',
 'doe_all',
 'etfg_samp',
 'etfgsamp',
 'execcomp',
 'factsamp_all',
 'factsamp_revere',
 'ff',
 'ff_all',
 'fisdsamp',
 'fisdsamp_all',
 'fjc',
 'fjc_linking',
 'fjc_litigation',
 'frb',
 'frb_all',
 'fssamp',
 'ftsesamp',
 'ftsesamp_russell_us',
 'gutenberg',
 'hfrsamp',
 'hfrsamp_hfrdb',
 'ibessamp_kpi',
 'ifgrsamp',
 'infasamp',
 'infogroupsamp_business',
 'infogroupsamp_residential',
 'infraclear_samp',
 'insdsamp',
 'iri',
 'iri_all',
 'kpisamp',
 'macrofin',
 'macrofin_comm_trade',
 'midas',
 'morningstarsamp_cisdm',
 'mpsych_sample',
 'mrktsamp',
 'mrktsamp_cds',
 'mrktsamp_cdx',
 'mrktsamp_msf',
 'mrktsamp_red',
 'msci_climate_samp',
 'msci_common_samp',
 'msci_esg_samp',
 'mscicoms',
 'mscicsmp',
 'msciesmp',
 'msrb',
 'msrb_all',
 'msrbsamp',
 'msrbsamp_all',
 'omtrial',
 'optionmsamp_europe',
 'optionmsamp_us',
 'otc',
 'otc_endofday',
 'panjiva_samp',
 'phlx',
 'phlx_all',
 'pitchsmp',
 'pnjvasmp',
 'preqsamp',
 'preqsamp_all',
 'public',
 'public_all',
 'pwt',
 'pwt_all',
 'reprisk',
 'reprisk_common',
 'reprisk_pm',
 'reprisk_sample',
 'reprisk_std',
 'reprisk_v2',
 'repsamp',
 'revelio_samp',
 'revsamp',
 'risksamp',
 'risksamp_all',
 'rq_all',
 'rstat_samp',
 'rstatsmp',
 'sdcsamp',
 'shvlsamp',
 'snapsamp',
 'snlsamp',
 'snlsamp_fig',
 'sustainalyticssamp_all',
 'sustsamp',
 'taqmsamp',
 'taqmsamp_all',
 'taqsamp',
 'taqsamp_all',
 'totalq',
 'totalq_all',
 'tr_sdc_samples',
 'trace',
 'trace_enhanced',
 'trace_standard',
 'trcstsmp',
 'trdbdmismp',
 'trdbwbsmp',
 'trdssamp',
 'tresgsmp',
 'trsamp',
 'trsamp_all',
 'trsamp_db_dmi',
 'trsamp_db_wb',
 'trsamp_ds_eq',
 'trsamp_dscom',
 'trsamp_dsecon',
 'trsamp_dsfut',
 'trsamp_esg',
 'trsamp_sdc_ma',
 'trsamp_sdc_ni',
 'trsamp_worldscope',
 'trucost_samp',
 'twoiq_samp',
 'twoiqsmp',
 'wabssamp',
 'wappsamp',
 'wenvsmp',
 'wmfsmp',
 'wrds_abs_samp',
 'wrds_environmental_samp',
 'wrds_insiders_samp',
 'wrds_mutualfund_samp',
 'wrds_shortvolume_samp',
 'wrdsapps',
 'wrdsapps_eushort',
 'wrdsapps_evtstudy_int',
 'wrdsapps_link_comp_eushort',
 'wrdsapps_patents',
 'wrdsapps_plink_exec_boardex',
 'wrdsapps_subsidiary',
 'wrdsapps_windices',
 'wrdsappssamp_all',
 'wrdssec_midas',
 'zacksamp',
 'zacksamp_all']

In [ ]:
conn.list_tables(library='boardex_eur')

['eur_board_characteristics',
 'eur_board_dir_announcements',
 'eur_board_dir_committees',
 'eur_board_education_assoc',
 'eur_board_listed_assoc',
 'eur_board_nfp_assoc',
 'eur_board_other_assoc',
 'eur_board_unlisted_assoc',
 'eur_company_profile_advisors',
 'eur_company_profile_details',
 'eur_company_profile_market_cap',
 'eur_company_profile_sr_mgrs',
 'eur_company_profile_stocks',
 'eur_dir_characteristics',
 'eur_dir_education_assoc',
 'eur_dir_listed_assoc',
 'eur_dir_nfp_assoc',
 'eur_dir_other_assoc',
 'eur_dir_profile_achievements',
 'eur_dir_profile_details',
 'eur_dir_profile_education',
 'eur_dir_profile_emp',
 'eur_dir_profile_other_activ',
 'eur_dir_standard_remun',
 'eur_dir_unlisted_assoc',
 'eur_lookupcompany',
 'eur_lookuproles',
 'eur_lookupsalutations',
 'eur_ltip_compensation',
 'eur_ltip_wealth',
 'eur_options_compensation',
 'eur_options_wealth',
 'eur_wrds_company_dir_names',
 'eur_wrds_company_names',
 'eur_wrds_company_networks',
 'eur_wrds_company_profile',
 'eur_wrds_company_region',
 'eur_wrds_dir_profile_all',
 'eur_wrds_dir_profile_emp',
 'eur_wrds_individual_networks',
 'eur_wrds_org_composition',
 'eur_wrds_org_summary']

### **3.2 Data Visualization**

---

## **4. Data Preprocessing**

### **4.1 Data Cleaning**

#### **4.1.1 Missing Values**

#### **4.1.2 Duplicated Values**

#### **4.1.3 Outliers**

### **4.2 Feature Selection**

---

## **5. Causal Inference**

---

## **6. Supervised Learning**

---

## **7. Unsupervised Learning**

---

## **8. Results and Conclusion**

---

---
## 7. Results *(complete for final submission)*

### 7a. Causal Inference

In [ ]:
# Causal inference analysis

### 7b. Supervised Learning

In [ ]:
# Supervised learning analysis

### 7c. Unsupervised / Generative

In [ ]:
# Unsupervised / generative analysis

## 8. Discussion & Conclusion *(complete for final submission)*

*Synthesise findings across all three method blocks. What does each lens reveal that the others miss? What are the limitations of your analysis?*